import { useAuthStore } from '@/stores'
const API_BASE=import.meta.env.VITE_API_URL||'https://mindsteps-backend.onrender.com'
async function call<T>(path:string,options:{method?:'GET'|'POST';body?:unknown}={}):Promise<T>{const {token}=useAuthStore.getState();const r=await fetch(`${API_BASE}${path}`,{method:options.method||'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:options.body?JSON.stringify(options.body):undefined});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.message||`HTTP ${r.status}`);return p as T}
export interface IndependenceSummary{checks:number;assistedChecks?:number;independentChecks?:number;comparableChecks:number;assistedScore:number;independentScore:number;assistanceGap:number;attemptBeforeHelpShare:number;averageHelpLevel:number;independenceScore:number;offloadingRisk:'low'|'medium'|'high'|'unknown';notice:string}
export interface TransferCheck{id:string;subject?:string|null;skill?:string|null;source:string;assisted_score?:number|null;independent_score?:number|null;help_level:number;attempt_before_help:boolean;completed:boolean;created_at:string;metadata?:Record<string,unknown>}
export interface IndependentChallenge{question:string;rubric:string[];expectedMinutes:number}
export interface IndependentEvaluation{score:number;feedback:string;evidence:string[];passed:boolean}
export type AutonomyTrend='improving'|'stable'|'attention'|'insufficient'
export interface AutonomyTrendResult{trend:AutonomyTrend;label:string;detail:string;delta:number|null;recentGap:number|null;previousGap:number|null;independentDelta:number|null}
const avg=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0
export function calculateAutonomyTrend(checks:TransferCheck[]):AutonomyTrendResult{const independent=checks.filter(c=>c.completed&&c.independent_score!=null).sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime());if(independent.length<2)return{trend:'insufficient',label:'Construindo histórico',detail:'Faça mais checks sem ajuda para enxergar uma tendência. Um resultado isolado não define sua aprendizagem.',delta:null,recentGap:null,previousGap:null,independentDelta:null};const half=Math.max(1,Math.floor(independent.length/2));const previous=independent.slice(0,half);const recent=independent.slice(half);const independentDelta=Math.round(avg(recent.map(c=>Number(c.independent_score)))-avg(previous.map(c=>Number(c.independent_score))));const comparable=checks.filter(c=>c.completed&&c.assisted_score!=null&&c.independent_score!=null).sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime());let recentGap:number|null=null,previousGap:number|null=null,delta:number|null=null;if(comparable.length>=2){const h=Math.max(1,Math.floor(comparable.length/2));previousGap=Math.round(avg(comparable.slice(0,h).map(c=>Number(c.assisted_score)-Number(c.independent_score))));recentGap=Math.round(avg(comparable.slice(h).map(c=>Number(c.assisted_score)-Number(c.independent_score))));delta=recentGap-previousGap}if(delta!=null&&delta<=-4)return{trend:'improving',label:'Gap diminuindo',detail:'Você está levando mais do treino para situações sem ajuda. Continue alternando prática assistida e checks independentes.',delta,recentGap,previousGap,independentDelta};if(delta!=null&&delta>=4)return{trend:'attention',label:'Gap aumentando',detail:'A diferença cresceu recentemente. Isso não é julgamento: pode ser hora de reduzir ajuda aos poucos e fazer mais recuperação sem consulta.',delta,recentGap,previousGap,independentDelta};if(independentDelta>=5)return{trend:'improving',label:'Independência crescendo',detail:'Seu desempenho sem ajuda melhorou nas evidências mais recentes.',delta,recentGap,previousGap,independentDelta};if(independentDelta<=-5)return{trend:'attention',label:'Vale observar',detail:'Os checks recentes ficaram abaixo dos anteriores. Revise o conteúdo e teste novamente antes de tirar conclusões.',delta,recentGap,previousGap,independentDelta};return{trend:'stable',label:'Estável',detail:'As evidências recentes estão próximas das anteriores. Continue acumulando checks para enxergar uma tendência mais confiável.',delta,recentGap,previousGap,independentDelta}}
export const independentLearningApi={summary:()=>call<{checks:TransferCheck[];summary:IndependenceSummary}>('/api/learning-os/transfer-checks'),save:(data:{subject?:string;skill?:string;source?:string;assistedScore?:number;independentScore?:number;helpLevel?:number;attemptBeforeHelp?:boolean;completed?:boolean;metadata?:Record<string,unknown>})=>call<{check:TransferCheck}>('/api/learning-os/transfer-checks',{method:'POST',body:data}),challenge:(data:{subject:string;skill?:string;context?:string})=>call<{challenge:IndependentChallenge}>('/api/learning-os/transfer-challenge',{method:'POST',body:data}),evaluate:(data:{question:string;answer:string;subject:string;skill?:string;rubric?:string[];assistedScore?:number;helpLevel?:number;attemptBeforeHelp?:boolean;source?:string})=>call<{evaluation:IndependentEvaluation;check:TransferCheck;summary:IndependenceSummary}>('/api/learning-os/transfer-challenge/evaluate',{method:'POST',body:data})}
