import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { BookOpenCheck, ChevronRight, Compass, FileText, Sparkles, Target } from 'lucide-react'

const areas=[
 {name:'Linguagens',value:62,tone:'bg-fuchsia-500',skills:['Inferência','Gêneros textuais','Coesão','Leitura crítica']},
 {name:'Humanas',value:55,tone:'bg-amber-500',skills:['Contexto histórico','Geopolítica','Cidadania','Interpretação de fontes']},
 {name:'Natureza',value:48,tone:'bg-emerald-500',skills:['Ecologia','Energia','Química cotidiana','Saúde']},
 {name:'Matemática',value:58,tone:'bg-cyan-500',skills:['Porcentagem','Funções','Proporção','Estatística']},
 {name:'Redação',value:64,tone:'bg-violet-500',skills:['Tese','Argumentação','Repertório','Intervenção']},
]

export function EnemMapPage(){
 const navigate=useNavigate(); const ordered=useMemo(()=>[...areas].sort((a,b)=>a.value-b.value),[]); const focus=ordered[0]
 return <main className="ms-screen space-y-4 py-4">
  <section className="relative overflow-hidden rounded-[30px] bg-[#17152f] p-5 text-white"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-cyan-400/20 blur-2xl"/><div className="relative flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Meu mapa ENEM</p><h1 className="mt-2 text-2xl font-black">Veja onde avançar agora.</h1><p className="mt-2 text-sm leading-6 text-white/70">O mapa reúne sinais de questões, redação e simulados para transformar lacunas em próximos passos.</p></div><Compass className="h-8 w-8 text-cyan-300"/></div></section>
  <section className="grid grid-cols-2 gap-3"><div className="rounded-3xl bg-amber-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-amber-700">Foco recomendado</p><p className="mt-2 text-xl font-black text-amber-950">{focus.name}</p><p className="mt-1 text-xs leading-5 text-amber-900/70">É onde os sinais atuais mostram maior espaço para evolução.</p></div><div className="rounded-3xl bg-emerald-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Regra do mapa</p><p className="mt-2 text-lg font-black text-emerald-950">Sem rótulos.</p><p className="mt-1 text-xs leading-5 text-emerald-900/70">O mapa muda conforme você aprende.</p></div></section>
  <section><div className="mb-3"><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Áreas</p><h2 className="text-xl font-black">Seu panorama atual</h2></div><div className="space-y-3">{areas.map(area=><div key={area.name} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-black">{area.name}</p><p className="text-sm font-black text-slate-500">{area.value}</p></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${area.tone}`} style={{width:`${area.value}%`}}/></div><div className="mt-3 flex flex-wrap gap-1.5">{area.skills.map(skill=><span key={skill} className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] font-bold text-slate-500">{skill}</span>)}</div></div>)}</div></section>
  <section className="rounded-3xl bg-indigo-50 p-5"><div className="flex items-center gap-2 text-indigo-700"><Sparkles className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Próximo passo</span></div><h2 className="mt-2 text-lg font-black">Treino curto em {focus.name}</h2><p className="mt-1 text-sm leading-6 text-indigo-900/70">Comece por poucos minutos. O mapa deve responder ao aprendizado, não virar um boletim.</p><button onClick={()=>navigate('/enem/questoes')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-700 py-3.5 text-sm font-black text-white">Praticar agora <ChevronRight className="h-4 w-4"/></button></section>
  <section className="grid grid-cols-2 gap-3"><button onClick={()=>navigate('/enem/questoes')} className="rounded-3xl bg-white p-4 text-left shadow-sm"><BookOpenCheck className="h-5 w-5 text-cyan-600"/><p className="mt-3 text-sm font-black">Questões</p><p className="mt-1 text-xs text-slate-500">Geram sinais para o mapa.</p></button><button onClick={()=>navigate('/enem/redacao/dna')} className="rounded-3xl bg-white p-4 text-left shadow-sm"><FileText className="h-5 w-5 text-violet-600"/><p className="mt-3 text-sm font-black">DNA da escrita</p><p className="mt-1 text-xs text-slate-500">Aprofunda sua evolução textual.</p></button></section>
  <section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-cyan-300"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Evolução futura</span></div><p className="mt-2 text-sm leading-6 text-slate-400">Nesta primeira camada os sinais são locais e pedagógicos. A sincronização com backend permitirá consolidar o mapa entre dispositivos, escolas e programas sem apagar o histórico individual.</p></section>
 </main>
}
