import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Clock3, Flag, Pause, Play, RotateCcw, Target, TimerReset } from 'lucide-react'
import { useEnemStore, type EnemArea, type EnemSimulationAreaResult } from '@/stores/enem'

type Area = Exclude<EnemArea,'Redação'>
type SimQuestion={id:string;area:Area;skill:string;text:string;options:string[];answer:number;difficulty:1|2|3}
type AnswerMap=Record<string,number|undefined>

const questions:SimQuestion[]=[
 {id:'sim-l1',area:'Linguagens',skill:'Inferência',text:'Quando o sentido principal depende de pistas não literais, a habilidade central é:',options:['memorização','inferência','cópia','classificação'],answer:1,difficulty:2},
 {id:'sim-l2',area:'Linguagens',skill:'Leitura crítica',text:'Diante de dois textos com teses opostas, o melhor critério de comparação é:',options:['tamanho','quantidade de palavras difíceis','qualidade dos argumentos e evidências','ordem de publicação'],answer:2,difficulty:3},
 {id:'sim-h1',area:'Humanas',skill:'Fonte histórica',text:'Uma fonte produzida por um governo deve ser analisada considerando:',options:['apenas a data','contexto, autoria e finalidade','somente seu valor artístico','se concorda com o leitor'],answer:1,difficulty:2},
 {id:'sim-h2',area:'Humanas',skill:'Cidadania',text:'Uma política pública se diferencia de uma decisão privada porque:',options:['não possui objetivo','responde a problemas coletivos com ação institucional','vale apenas para empresas','não envolve recursos públicos'],answer:1,difficulty:2},
 {id:'sim-n1',area:'Natureza',skill:'Ecologia',text:'A remoção de um predador de topo pode causar:',options:['equilíbrio automático','efeitos em cascata na cadeia alimentar','somente aumento de decompositores','nenhuma mudança'],answer:1,difficulty:2},
 {id:'sim-n2',area:'Natureza',skill:'Evidência científica',text:'Uma hipótese ganha força científica quando:',options:['é repetida muitas vezes','é apoiada por evidências reproduzíveis','é defendida por uma pessoa famosa','não pode ser testada'],answer:1,difficulty:3},
 {id:'sim-m1',area:'Matemática',skill:'Proporção',text:'Se 4 ingressos custam R$ 60 no mesmo preço unitário, 10 custam:',options:['R$ 120','R$ 130','R$ 140','R$ 150'],answer:3,difficulty:2},
 {id:'sim-m2',area:'Matemática',skill:'Modelagem',text:'Um serviço cobra R$ 12 fixos mais R$ 3 por unidade. Para 6 unidades, o total é:',options:['R$ 18','R$ 24','R$ 30','R$ 36'],answer:2,difficulty:2},
]
const areaOrder:Area[]=['Linguagens','Humanas','Natureza','Matemática']

export function EnemSimulationPage(){
 const navigate=useNavigate(); const {simulations,recordSimulation,recordAttempt}=useEnemStore()
 const [phase,setPhase]=useState<'intro'|'run'|'review'|'result'>('intro'); const [index,setIndex]=useState(0); const [paused,setPaused]=useState(false); const [elapsed,setElapsed]=useState(0); const [answers,setAnswers]=useState<AnswerMap>({}); const [marked,setMarked]=useState<string[]>([]); const [reviewChanges,setReviewChanges]=useState(0); const [result,setResult]=useState<{correct:number;strategy:number;areas:EnemSimulationAreaResult[]}|null>(null)
 const questionStartedAt=useRef(Date.now()); const timeByQuestion=useRef<Record<string,number>>({})
 useEffect(()=>{if(phase!=='run'||paused)return;const id=window.setInterval(()=>setElapsed(e=>e+1),1000);return()=>window.clearInterval(id)},[phase,paused])
 const q=questions[index]
 const answeredCount=Object.values(answers).filter(v=>v!==undefined).length
 const saveTime=()=>{if(!q)return;const seconds=Math.max(1,Math.round((Date.now()-questionStartedAt.current)/1000));timeByQuestion.current[q.id]=(timeByQuestion.current[q.id]||0)+seconds;questionStartedAt.current=Date.now()}
 const choose=(option:number)=>{if(phase!=='run')return;setAnswers(a=>({...a,[q.id]:option}))}
 const toggleMark=()=>setMarked(m=>m.includes(q.id)?m.filter(id=>id!==q.id):[...m,q.id])
 const go=(next:number)=>{saveTime();setIndex(Math.max(0,Math.min(questions.length-1,next)))}
 const skip=()=>{saveTime();if(index===questions.length-1)setPhase('review');else setIndex(i=>i+1)}
 const openReview=()=>{saveTime();setPhase('review')}
 const reviewSelect=(question:SimQuestion,option:number)=>{const before=answers[question.id];if(before!==undefined&&before!==option)setReviewChanges(c=>c+1);setAnswers(a=>({...a,[question.id]:option}))}
 const finish=()=>{
   const correct=questions.filter(item=>answers[item.id]===item.answer).length
   const skipped=questions.length-answeredCount
   const areas:EnemSimulationAreaResult[]=areaOrder.map(area=>{const qs=questions.filter(item=>item.area===area);return {area,answered:qs.filter(item=>answers[item.id]!==undefined).length,correct:qs.filter(item=>answers[item.id]===item.answer).length,skipped:qs.filter(item=>answers[item.id]===undefined).length,marked:qs.filter(item=>marked.includes(item.id)).length,secondsSpent:qs.reduce((s,item)=>s+(timeByQuestion.current[item.id]||0),0)}})
   questions.forEach(item=>{const value=answers[item.id];if(value!==undefined)recordAttempt({questionId:item.id,area:item.area,skill:item.skill,correct:value===item.answer,difficulty:item.difficulty})})
   const accuracy=correct/questions.length;const completion=answeredCount/questions.length;const markControl=marked.length?Math.max(0,1-Math.max(0,marked.length-3)/questions.length):1;const strategy=Math.round((accuracy*.55+completion*.25+markControl*.2)*100)
   recordSimulation({elapsedSeconds:elapsed,markedQuestions:marked.length,answeredQuestions:answeredCount,correctQuestions:correct,skippedQuestions:skipped,reviewChanges,areaResults:areas,strategyScore:strategy});setResult({correct,strategy,areas});setPhase('result')
 }
 const reset=()=>{setPhase('intro');setIndex(0);setPaused(false);setElapsed(0);setAnswers({});setMarked([]);setReviewChanges(0);setResult(null);timeByQuestion.current={};questionStartedAt.current=Date.now()}
 const recent=simulations[0]
 const currentArea=useMemo(()=>q?.area,[q])
 return <main className="ms-screen space-y-4 py-4">
  <section className="rounded-[30px] bg-gradient-to-br from-amber-500 via-orange-600 to-rose-600 p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-100">Simulado estratégico</p><h1 className="mt-2 text-2xl font-black">Treine conhecimento + decisão.</h1></div><TimerReset className="h-8 w-8 text-white/90"/></div><p className="mt-3 text-sm leading-6 text-white/80">Agora o simulado registra desempenho por área, marcações, questões puladas, revisão e tempo.</p></section>
  {phase==='intro'&&<><section className="rounded-3xl bg-white p-5 shadow-sm"><div className="grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xl font-black">{questions.length}</p><p className="text-[10px] font-bold text-slate-400">questões</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xl font-black">4</p><p className="text-[10px] font-bold text-slate-400">áreas</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xl font-black">{simulations.length}</p><p className="text-[10px] font-bold text-slate-400">sessões</p></div></div><p className="mt-4 text-sm leading-6 text-slate-500">Você pode responder, pular ou marcar para revisar. O importante não é só acertar: é administrar dúvida e tempo.</p>{recent?.strategyScore!==undefined&&<div className="mt-4 rounded-2xl bg-indigo-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-indigo-700">Última estratégia</p><p className="mt-1 text-2xl font-black text-indigo-950">{recent.strategyScore}/100</p></div>}<button onClick={()=>{setPhase('run');questionStartedAt.current=Date.now()}} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white"><Play className="h-4 w-4"/>Iniciar simulado curto</button></section><section className="rounded-3xl bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-indigo-700">Estratégia</p><p className="mt-2 text-sm leading-6 text-indigo-900/75">Se travar, marque e siga. Depois revise com o tempo restante. Queremos descobrir como você decide sob pressão.</p></section></>}
  {phase==='run'&&<><section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">{currentArea} · {q.skill}</p><h2 className="mt-1 text-lg font-black">Questão {index+1} de {questions.length}</h2></div><div className="flex items-center gap-2 text-amber-700"><Clock3 className="h-4 w-4"/><span className="text-sm font-black">{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</span></div></div><p className="mt-4 text-base font-black leading-7">{q.text}</p><div className="mt-4 space-y-2">{q.options.map((option,i)=><button key={option} onClick={()=>choose(i)} className={`w-full rounded-2xl border p-4 text-left text-sm font-bold ${answers[q.id]===i?'border-indigo-400 bg-indigo-50 text-indigo-950':'border-slate-100 bg-slate-50 text-slate-800'}`}>{String.fromCharCode(65+i)}. {option}</button>)}</div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={toggleMark} className={`flex items-center justify-center gap-1 rounded-2xl py-3 text-xs font-black ${marked.includes(q.id)?'bg-rose-100 text-rose-800':'bg-slate-100 text-slate-700'}`}><Flag className="h-3 w-3"/>Marcar</button><button onClick={skip} className="rounded-2xl bg-amber-50 py-3 text-xs font-black text-amber-800">Pular</button><button onClick={()=>setPaused(p=>!p)} className="flex items-center justify-center gap-1 rounded-2xl bg-slate-950 py-3 text-xs font-black text-white">{paused?<Play className="h-3 w-3"/>:<Pause className="h-3 w-3"/>}{paused?'Retomar':'Pausar'}</button></div><div className="mt-3 flex items-center justify-between"><button disabled={index===0} onClick={()=>go(index-1)} className="text-xs font-black text-slate-400 disabled:opacity-30">← anterior</button>{index===questions.length-1?<button onClick={openReview} className="text-xs font-black text-indigo-700">Revisar prova →</button>:<button onClick={()=>go(index+1)} className="text-xs font-black text-indigo-700">próxima →</button>}</div></section><section className="grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-emerald-50 p-3"><p className="text-xl font-black text-emerald-800">{answeredCount}</p><p className="text-[10px] font-bold text-emerald-900/60">respondidas</p></div><div className="rounded-2xl bg-rose-50 p-3"><p className="text-xl font-black text-rose-800">{marked.length}</p><p className="text-[10px] font-bold text-rose-900/60">marcadas</p></div><div className="rounded-2xl bg-amber-50 p-3"><p className="text-xl font-black text-amber-800">{questions.length-answeredCount}</p><p className="text-[10px] font-bold text-amber-900/60">em aberto</p></div></section></>}
  {phase==='review'&&<><section className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-violet-700">Revisão estratégica</p><h2 className="mt-2 text-xl font-black">Volte só onde vale a pena.</h2><p className="mt-1 text-sm leading-6 text-slate-500">Marcadas aparecem primeiro; questões em branco também merecem decisão final.</p><div className="mt-4 space-y-3">{[...questions].sort((a,b)=>Number(marked.includes(b.id))-Number(marked.includes(a.id))).map(item=><div key={item.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center justify-between"><p className="text-xs font-black text-slate-500">{item.area} · {item.skill}</p><div className="flex gap-1">{marked.includes(item.id)&&<span className="rounded-full bg-rose-50 px-2 py-1 text-[10px] font-black text-rose-700">MARCADA</span>}{answers[item.id]===undefined&&<span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-700">EM BRANCO</span>}</div></div><p className="mt-2 text-sm font-bold">{item.text}</p><div className="mt-3 grid grid-cols-2 gap-2">{item.options.map((option,i)=><button key={option} onClick={()=>reviewSelect(item,i)} className={`rounded-xl p-2 text-left text-xs font-bold ${answers[item.id]===i?'bg-indigo-100 text-indigo-900':'bg-slate-50 text-slate-600'}`}>{String.fromCharCode(65+i)}. {option}</button>)}</div></div>)}</div></section><button onClick={finish} className="w-full rounded-2xl bg-slate-950 py-4 text-sm font-black text-white">Finalizar simulado e analisar estratégia</button></>}
  {phase==='result'&&result&&<><section className="rounded-3xl bg-emerald-50 p-5"><div className="flex items-center gap-2 text-emerald-700"><CheckCircle2 className="h-5 w-5"/><span className="text-xs font-black uppercase tracking-wider">Sessão registrada</span></div><h2 className="mt-2 text-2xl font-black text-emerald-950">Estratégia {result.strategy}/100</h2><p className="mt-2 text-sm leading-6 text-emerald-900/70">{result.correct}/{questions.length} acertos · {reviewChanges} mudanças na revisão · {marked.length} marcações.</p></section><section className="space-y-2">{result.areas.map(area=><div key={area.area} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-black">{area.area}</p><p className="text-sm font-black text-slate-500">{area.correct}/{Math.max(1,area.answered)} acertos</p></div><div className="mt-2 grid grid-cols-3 gap-2 text-center text-[10px] font-bold text-slate-400"><span>{area.skipped} puladas</span><span>{area.marked} marcadas</span><span>{area.secondsSpent}s</span></div></div>)}</section><section className="rounded-3xl bg-violet-50 p-5"><div className="flex items-center gap-2 text-violet-700"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">O que aprendemos</span></div><p className="mt-2 text-sm leading-6 text-violet-900/75">As respostas deste simulado já foram registradas como novas evidências por habilidade. Seu mapa e o Meu Dia ENEM podem mudar agora.</p></section><div className="grid grid-cols-2 gap-3"><button onClick={reset} className="flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white py-3 text-sm font-black"><RotateCcw className="h-4 w-4"/>Novo simulado</button><button onClick={()=>navigate('/enem/mapa')} className="flex items-center justify-center gap-2 rounded-2xl bg-indigo-700 py-3 text-sm font-black text-white">Ver mapa <ArrowRight className="h-4 w-4"/></button></div></>}
 </main>
}
