import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Clock3, Flag, Pause, Play, Target, TimerReset } from 'lucide-react'

const blocks=[
 {name:'Linguagens',minutes:45,questions:15},{name:'Humanas',minutes:40,questions:15},{name:'Natureza',minutes:45,questions:15},{name:'Matemática',minutes:50,questions:15},
]

export function EnemSimulationPage(){
 const navigate=useNavigate(); const [started,setStarted]=useState(false); const [paused,setPaused]=useState(false); const [elapsed,setElapsed]=useState(0); const [marked,setMarked]=useState(0)
 const totalMinutes=useMemo(()=>blocks.reduce((s,b)=>s+b.minutes,0),[]); const totalQuestions=useMemo(()=>blocks.reduce((s,b)=>s+b.questions,0),[])
 return <main className="ms-screen space-y-4 py-4">
  <section className="rounded-[30px] bg-gradient-to-br from-amber-500 via-orange-600 to-rose-600 p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-100">Simulado estratégico</p><h1 className="mt-2 text-2xl font-black">Treine prova, tempo e decisão.</h1></div><TimerReset className="h-8 w-8 text-white/90"/></div><p className="mt-3 text-sm leading-6 text-white/80">Não queremos só contar acertos. O simulado deve ensinar quando insistir, quando pular e como distribuir energia.</p></section>
  {!started?<><section className="rounded-3xl bg-white p-5 shadow-sm"><div className="grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xl font-black">{totalQuestions}</p><p className="text-[10px] font-bold text-slate-400">questões</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xl font-black">{totalMinutes}</p><p className="text-[10px] font-bold text-slate-400">minutos</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xl font-black">4</p><p className="text-[10px] font-bold text-slate-400">blocos</p></div></div><div className="mt-4 space-y-2">{blocks.map(b=><div key={b.name} className="flex items-center justify-between rounded-2xl border border-slate-100 p-3"><div><p className="text-sm font-black">{b.name}</p><p className="text-xs text-slate-500">{b.questions} questões</p></div><span className="text-xs font-black text-amber-700">{b.minutes} min</span></div>)}</div><button onClick={()=>setStarted(true)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white"><Play className="h-4 w-4"/>Iniciar treino</button></section><section className="rounded-3xl bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-indigo-700">Estratégia antes da prova</p><p className="mt-2 text-sm leading-6 text-indigo-900/75">Marque uma questão quando estiver em dúvida e siga em frente. O objetivo é treinar decisão sob tempo, não heroísmo em uma única questão.</p></section></>:
  <><section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Sessão ativa</p><h2 className="mt-1 text-lg font-black">Bloco 1 · Linguagens</h2></div><Clock3 className="h-6 w-6 text-amber-600"/></div><div className="mt-4 rounded-2xl bg-slate-950 p-5 text-center text-white"><p className="text-4xl font-black tabular-nums">{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</p><p className="mt-1 text-xs text-slate-400">tempo simulado</p></div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>setElapsed(e=>e+60)} className="rounded-2xl bg-slate-50 py-3 text-xs font-black">+1 min</button><button onClick={()=>setPaused(p=>!p)} className="flex items-center justify-center gap-1 rounded-2xl bg-amber-50 py-3 text-xs font-black text-amber-800">{paused?<Play className="h-3 w-3"/>:<Pause className="h-3 w-3"/>}{paused?'Retomar':'Pausar'}</button><button onClick={()=>setMarked(m=>m+1)} className="flex items-center justify-center gap-1 rounded-2xl bg-rose-50 py-3 text-xs font-black text-rose-800"><Flag className="h-3 w-3"/>Marcar</button></div></section><section className="grid grid-cols-2 gap-3"><div className="rounded-3xl bg-amber-50 p-4"><p className="text-2xl font-black text-amber-800">{marked}</p><p className="mt-1 text-xs font-bold text-amber-900/70">questões marcadas para voltar</p></div><div className="rounded-3xl bg-emerald-50 p-4"><p className="text-2xl font-black text-emerald-800">{Math.max(0,45-Math.floor(elapsed/60))}</p><p className="mt-1 text-xs font-bold text-emerald-900/70">minutos no bloco</p></div></section><section className="rounded-3xl bg-violet-50 p-5"><div className="flex items-center gap-2 text-violet-700"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Leitura de estratégia</span></div><p className="mt-2 text-sm leading-6 text-violet-900/70">Depois da sessão, o MindSteps vai cruzar tempo, acertos e marcações para detectar questões em que você gastou energia demais, respondeu rápido demais ou tomou boas decisões.</p></section><button onClick={()=>navigate('/enem/mapa')} className="w-full rounded-2xl bg-slate-950 py-4 text-sm font-black text-white">Encerrar e ver mapa</button></>}
 </main>
}
