import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { BookOpenCheck, ChevronRight, Compass, FileText, Sparkles, Target } from 'lucide-react'
import { useEnemStore, type EnemArea } from '@/stores/enem'
import { useWritingStore } from '@/stores/writing'
import { analyzeWriting } from '@/lib/writingAnalysis'

const labels:Record<EnemArea,string[]>={Linguagens:['Inferência','Gêneros textuais','Coesão','Leitura crítica'],Humanas:['Contexto histórico','Geopolítica','Cidadania','Interpretação de fontes'],Natureza:['Ecologia','Energia','Química cotidiana','Saúde'],Matemática:['Porcentagem','Funções','Proporção','Estatística'],Redação:['Tese','Argumentação','Repertório','Intervenção']}
const tones:Record<EnemArea,string>={Linguagens:'bg-fuchsia-500',Humanas:'bg-amber-500',Natureza:'bg-emerald-500',Matemática:'bg-cyan-500',Redação:'bg-violet-500'}

export function EnemMapPage(){
 const navigate=useNavigate(); const {attempts}=useEnemStore(); const {projects}=useWritingStore()
 const areas=useMemo(()=>{
   const base:Record<EnemArea,number>={Linguagens:50,Humanas:50,Natureza:50,Matemática:50,Redação:50}
   ;(['Linguagens','Humanas','Natureza','Matemática'] as EnemArea[]).forEach(area=>{const list=attempts.filter(a=>a.area===area).slice(-20);if(list.length){const acc=list.filter(a=>a.correct).length/list.length;base[area]=Math.round(30+acc*70)}})
   const writing=projects.filter(p=>p.versions.length).slice(0,5);if(writing.length){const vals=writing.map(p=>analyzeWriting(p.versions.at(-1)!.text));base.Redação=Math.round(vals.reduce((sum,v)=>sum+Object.values(v.scores).reduce((a,b)=>a+b,0)/6,0)/vals.length)}
   return (Object.keys(base) as EnemArea[]).map(name=>({name,value:base[name],tone:tones[name],skills:labels[name]}))
 },[attempts,projects])
 const ordered=useMemo(()=>[...areas].sort((a,b)=>a.value-b.value),[areas]); const focus=ordered[0]
 return <main className="ms-screen space-y-4 py-4">
  <section className="relative overflow-hidden rounded-[30px] bg-[#17152f] p-5 text-white"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-cyan-400/20 blur-2xl"/><div className="relative flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Meu mapa ENEM</p><h1 className="mt-2 text-2xl font-black">Veja onde avançar agora.</h1><p className="mt-2 text-sm leading-6 text-white/70">Questões e redações reais já mudam este mapa. Quanto mais você pratica, menos genérico ele fica.</p></div><Compass className="h-8 w-8 text-cyan-300"/></div></section>
  <section className="grid grid-cols-2 gap-3"><div className="rounded-3xl bg-amber-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-amber-700">Foco recomendado</p><p className="mt-2 text-xl font-black text-amber-950">{focus.name}</p><p className="mt-1 text-xs leading-5 text-amber-900/70">É onde os sinais atuais mostram maior espaço para evolução.</p></div><div className="rounded-3xl bg-emerald-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Regra do mapa</p><p className="mt-2 text-lg font-black text-emerald-950">Sem rótulos.</p><p className="mt-1 text-xs leading-5 text-emerald-900/70">O mapa muda conforme você aprende.</p></div></section>
  <section><div className="mb-3"><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Áreas</p><h2 className="text-xl font-black">Seu panorama atual</h2></div><div className="space-y-3">{areas.map(area=><div key={area.name} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-black">{area.name}</p><p className="text-sm font-black text-slate-500">{area.value}</p></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${area.tone}`} style={{width:`${area.value}%`}}/></div><div className="mt-3 flex flex-wrap gap-1.5">{area.skills.map(skill=><span key={skill} className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] font-bold text-slate-500">{skill}</span>)}</div></div>)}</div></section>
  <section className="rounded-3xl bg-indigo-50 p-5"><div className="flex items-center gap-2 text-indigo-700"><Sparkles className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Próximo passo</span></div><h2 className="mt-2 text-lg font-black">Treino curto em {focus.name}</h2><p className="mt-1 text-sm leading-6 text-indigo-900/70">O Meu Dia ENEM usa este mesmo foco para montar a sessão curta de hoje.</p><button onClick={()=>navigate('/enem/hoje')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-700 py-3.5 text-sm font-black text-white">Abrir meu plano <ChevronRight className="h-4 w-4"/></button></section>
  <section className="grid grid-cols-2 gap-3"><button onClick={()=>navigate('/enem/questoes')} className="rounded-3xl bg-white p-4 text-left shadow-sm"><BookOpenCheck className="h-5 w-5 text-cyan-600"/><p className="mt-3 text-sm font-black">Questões</p><p className="mt-1 text-xs text-slate-500">{attempts.length} respostas alimentando o mapa.</p></button><button onClick={()=>navigate('/enem/redacao/dna')} className="rounded-3xl bg-white p-4 text-left shadow-sm"><FileText className="h-5 w-5 text-violet-600"/><p className="mt-3 text-sm font-black">DNA da escrita</p><p className="mt-1 text-xs text-slate-500">{projects.filter(p=>p.versions.length).length} textos com sinal.</p></button></section>
  <section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-cyan-300"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Motor em construção</span></div><p className="mt-2 text-sm leading-6 text-slate-400">Esta versão já usa histórico local real. O backend consolidará os mesmos sinais entre dispositivos e instituições sem apagar a trajetória individual.</p></section>
 </main>
}
