import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, CheckCircle2, ChevronRight, Lightbulb, RotateCcw, Target, XCircle } from 'lucide-react'

type Question = { id:string; area:string; skill:string; text:string; options:string[]; answer:number; explanation:string; difficulty:1|2|3 }
const bank:Question[]=[
{id:'q1',area:'Matemática',skill:'Porcentagem',text:'Uma loja aplica desconto de 20% em um produto de R$ 150. Qual é o preço final?',options:['R$ 100','R$ 110','R$ 120','R$ 130','R$ 140'],answer:2,explanation:'20% de 150 é 30. Então 150 − 30 = 120.',difficulty:1},
{id:'q2',area:'Ciências Humanas',skill:'Interpretação histórica',text:'Ao analisar uma fonte histórica, qual atitude ajuda mais a compreender seu significado?',options:['Ignorar o contexto','Observar autoria, época e finalidade','Ler apenas o título','Buscar uma resposta decorada','Comparar apenas datas'],answer:1,explanation:'Fontes históricas ganham significado quando autoria, contexto de produção e finalidade são considerados.',difficulty:1},
{id:'q3',area:'Linguagens',skill:'Inferência',text:'Quando um texto sugere uma ideia sem afirmá-la diretamente, o leitor precisa principalmente:',options:['Copiar uma frase','Inferir a partir de pistas','Contar palavras','Memorizar o autor','Trocar o gênero textual'],answer:1,explanation:'Inferência é construir sentido a partir de pistas explícitas e implícitas do texto.',difficulty:1},
{id:'q4',area:'Ciências da Natureza',skill:'Relações ecológicas',text:'A retirada de um predador de topo de uma cadeia alimentar pode provocar:',options:['Nenhuma alteração','Apenas aumento de plantas','Desequilíbrios em vários níveis tróficos','Fim imediato do ecossistema','Somente redução de decompositores'],answer:2,explanation:'Predadores de topo regulam populações; sua retirada pode gerar efeito em cascata em diferentes níveis tróficos.',difficulty:2},
]

export function EnemQuestionsPage(){
 const navigate=useNavigate(); const [index,setIndex]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [correct,setCorrect]=useState(0); const [history,setHistory]=useState<Array<{skill:string;ok:boolean}>>([])
 const q=bank[index%bank.length]; const answered=selected!==null; const accuracy=history.length?Math.round(correct/history.length*100):0
 const weak=useMemo(()=>{const grouped=new Map<string,{n:number,ok:number}>();history.forEach(h=>{const v=grouped.get(h.skill)||{n:0,ok:0};v.n++;if(h.ok)v.ok++;grouped.set(h.skill,v)});return [...grouped.entries()].sort((a,b)=>(a[1].ok/a[1].n)-(b[1].ok/b[1].n))[0]?.[0]},[history])
 const choose=(i:number)=>{if(answered)return;setSelected(i);const ok=i===q.answer;if(ok)setCorrect(c=>c+1);setHistory(h=>[...h,{skill:q.skill,ok}])}
 const next=()=>{setSelected(null);setIndex(i=>i+1)}
 return <main className="ms-screen space-y-4 py-4">
  <section className="rounded-[30px] bg-gradient-to-br from-cyan-600 via-blue-700 to-indigo-800 p-5 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-100">Questões adaptativas</p><h1 className="mt-2 text-2xl font-black">Pratique para descobrir o próximo passo.</h1><p className="mt-2 text-sm leading-6 text-white/75">O objetivo não é fazer uma fila infinita de questões. É identificar padrões de erro e transformar cada um em treino.</p></section>
  <section className="grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-white p-3 shadow-sm"><p className="text-xl font-black">{history.length}</p><p className="text-[10px] font-bold text-slate-400">respondidas</p></div><div className="rounded-2xl bg-white p-3 shadow-sm"><p className="text-xl font-black">{accuracy}%</p><p className="text-[10px] font-bold text-slate-400">acerto</p></div><div className="rounded-2xl bg-white p-3 shadow-sm"><p className="truncate text-sm font-black">{weak||'—'}</p><p className="text-[10px] font-bold text-slate-400">atenção</p></div></section>
  <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-black text-cyan-700">{q.area}</span><span className="text-xs font-bold text-slate-400">{q.skill}</span></div><h2 className="mt-4 text-lg font-black leading-7">{q.text}</h2><div className="mt-4 space-y-2">{q.options.map((o,i)=>{const isCorrect=i===q.answer,isSelected=i===selected;return <button key={o} onClick={()=>choose(i)} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left text-sm font-bold transition ${answered&&isCorrect?'border-emerald-300 bg-emerald-50 text-emerald-900':answered&&isSelected&&!isCorrect?'border-rose-300 bg-rose-50 text-rose-900':'border-slate-100 bg-slate-50 text-slate-800'}`}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-white text-xs font-black">{String.fromCharCode(65+i)}</span><span className="flex-1">{o}</span>{answered&&isCorrect&&<CheckCircle2 className="h-5 w-5 text-emerald-600"/>}{answered&&isSelected&&!isCorrect&&<XCircle className="h-5 w-5 text-rose-600"/>}</button>})}</div></section>
  {answered&&<section className={`rounded-3xl p-5 ${selected===q.answer?'bg-emerald-50':'bg-amber-50'}`}><div className="flex items-center gap-2"><Lightbulb className="h-5 w-5"/><p className="text-sm font-black">Entenda o raciocínio</p></div><p className="mt-2 text-sm leading-6 opacity-75">{q.explanation}</p><button onClick={next} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white">Próxima questão <ArrowRight className="h-4 w-4"/></button></section>}
  {weak&&history.length>=3&&<section className="rounded-3xl bg-violet-50 p-5"><div className="flex items-center gap-2 text-violet-700"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Sinal adaptativo</span></div><h2 className="mt-2 font-black">Vale reforçar {weak}.</h2><p className="mt-1 text-sm leading-6 text-violet-900/70">O MindSteps começa a enxergar onde você hesita. Depois vamos ligar esse sinal diretamente ao seu mapa ENEM e às missões diárias.</p></section>}
  <div className="grid grid-cols-2 gap-3"><button onClick={()=>{setIndex(0);setSelected(null);setCorrect(0);setHistory([])}} className="flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white py-3 text-sm font-black"><RotateCcw className="h-4 w-4"/>Recomeçar</button><button onClick={()=>navigate('/enem/mapa')} className="flex items-center justify-center gap-2 rounded-2xl bg-indigo-100 py-3 text-sm font-black text-indigo-800">Ver meu mapa <ChevronRight className="h-4 w-4"/></button></div>
 </main>
}
