import { useNavigate } from 'react-router-dom'
import { BookOpenCheck, BrainCircuit, CalendarDays, ChevronRight, Clock3, Dna, FileText, GraduationCap, RotateCcw, Shuffle, Sparkles, Target, TimerReset } from 'lucide-react'
import { useEnemStore } from '@/stores/enem'

const tools=[
 {title:'Minha Semana',subtitle:'Ritmo, sequência e meta semanal',icon:CalendarDays,path:'/enem/semana',tone:'bg-orange-50 text-orange-700'},
 {title:'Caderno de Erros',subtitle:'Transforme erros em revisão útil',icon:RotateCcw,path:'/enem/erros',tone:'bg-rose-50 text-rose-700'},
 {title:'Questões',subtitle:'Prática adaptativa por habilidade',icon:BookOpenCheck,path:'/enem/questoes',tone:'bg-cyan-50 text-cyan-700'},
 {title:'Simulado',subtitle:'Treine estratégia e tempo de prova',icon:TimerReset,path:'/enem/simulado',tone:'bg-amber-50 text-amber-700'},
 {title:'Coach de Estratégia',subtitle:'Aprenda a decidir melhor na prova',icon:BrainCircuit,path:'/enem/estrategia',tone:'bg-slate-100 text-slate-800'},
 {title:'Meu mapa ENEM',subtitle:'Veja forças, lacunas e próximos passos',icon:Target,path:'/enem/mapa',tone:'bg-emerald-50 text-emerald-700'},
 {title:'Redação',subtitle:'Aprenda a pensar, escrever e revisar',icon:FileText,path:'/enem/redacao',tone:'bg-violet-50 text-violet-700'},
 {title:'Coach de Escrita',subtitle:'Seu texto vira treino personalizado',icon:BrainCircuit,path:'/enem/redacao/coach',tone:'bg-indigo-50 text-indigo-700'},
 {title:'DNA da Escrita',subtitle:'Veja padrões, forças e próximo salto',icon:Dna,path:'/enem/redacao/dna',tone:'bg-fuchsia-50 text-fuchsia-700'},
 {title:'Motor de Temas',subtitle:'Treine diversidade e fuja da decoreba',icon:Shuffle,path:'/enem/redacao/temas',tone:'bg-rose-50 text-rose-700'},
]

export function EnemHubPage(){
 const navigate=useNavigate(); const {profile,diagnostic}=useEnemStore(); const primaryPath=!profile?'/enem/configurar':!diagnostic?'/enem/diagnostico':'/enem/hoje'; const primaryLabel=!profile?'Montar meu plano ENEM':!diagnostic?'Fazer diagnóstico inicial':'Começar meu dia ENEM'
 return <main className="ms-screen space-y-5 py-4"><section className="relative overflow-hidden rounded-[32px] bg-gradient-to-br from-indigo-700 via-violet-700 to-fuchsia-600 p-5 text-white shadow-xl shadow-violet-200/60"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-white/10 blur-2xl"/><div className="relative"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-[.2em] text-violet-100">MindSteps ENEM</span><GraduationCap className="h-7 w-7 text-white/90"/></div><h1 className="mt-4 text-3xl font-black tracking-tight">Seu ENEM, um passo por vez.</h1><p className="mt-3 text-sm leading-6 text-white/80">Você não precisa decidir o que estudar toda vez. O MindSteps transforma contexto, desempenho, erros e ritmo em um próximo passo claro.</p><button onClick={()=>navigate(primaryPath)} className="ms-pressable mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-white px-5 py-4 text-sm font-black text-violet-700">{primaryLabel} <ChevronRight className="h-5 w-5"/></button></div></section>
 {profile&&<section className="rounded-[28px] border border-violet-100 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-violet-600">Seu objetivo</p><h2 className="mt-2 text-lg font-black">{profile.targetCourse||profile.goal}</h2><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-lg font-black">{profile.targetScore}</p><p className="text-[10px] font-bold text-slate-400">meta</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-lg font-black">{profile.dailyMinutes}</p><p className="text-[10px] font-bold text-slate-400">min/dia</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-lg font-black">{profile.studyDaysPerWeek}x</p><p className="text-[10px] font-bold text-slate-400">semana</p></div></div><div className="mt-3 flex gap-3"><button onClick={()=>navigate('/enem/configurar')} className="text-xs font-black text-violet-700">Ajustar plano →</button>{!diagnostic&&<button onClick={()=>navigate('/enem/diagnostico')} className="text-xs font-black text-fuchsia-700">Fazer diagnóstico →</button>}</div></section>}
 {diagnostic&&<section className="rounded-[28px] border border-emerald-100 bg-emerald-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Primeiro mapa ativo</p><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-4"><p className="text-xs font-bold text-slate-400">acerto diagnóstico</p><p className="mt-1 text-2xl font-black text-emerald-800">{diagnostic.accuracy}%</p></div><div className="rounded-2xl bg-white p-4"><p className="text-xs font-bold text-slate-400">evidências iniciais</p><p className="mt-1 text-2xl font-black text-emerald-800">{diagnostic.questionCount+1}</p></div></div><button onClick={()=>navigate('/enem/mapa')} className="mt-3 text-sm font-black text-emerald-800">Ver meu primeiro mapa →</button></section>}
 <section className="rounded-[28px] border border-indigo-100 bg-gradient-to-br from-indigo-50 to-white p-5"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 text-white"><BrainCircuit className="h-5 w-5"/></span><div><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Motor adaptativo</p><h2 className="mt-1 text-lg font-black">Seu desempenho escolhe seu próximo treino.</h2><p className="mt-1 text-sm leading-5 text-slate-500">Redação, questões, simulados, erros e constância alimentam um mesmo sistema de aprendizagem.</p><button onClick={()=>navigate('/enem/mapa')} className="mt-3 text-sm font-black text-indigo-700">Abrir meu mapa →</button></div></div></section><section className="rounded-[28px] bg-slate-950 p-5 text-white"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/10 text-violet-300"><Clock3 className="h-5 w-5"/></span><div><p className="text-xs font-black uppercase tracking-wider text-violet-300">Meu Dia ENEM</p><h2 className="text-lg font-black">Pouco atrito. Um próximo passo claro.</h2></div></div><p className="mt-3 text-sm leading-6 text-slate-400">Seu ritmo começa pela disponibilidade que você informou e ganha precisão conforme surgem evidências reais.</p><button onClick={()=>navigate(primaryPath)} className="mt-4 w-full rounded-2xl bg-violet-500 py-3.5 text-sm font-black">{primaryLabel} →</button></section><section><div className="mb-3"><p className="text-xs font-black uppercase tracking-wider text-violet-600">Seu kit ENEM</p><h2 className="text-xl font-black text-slate-950">Treine o que realmente precisa</h2></div><div className="grid grid-cols-2 gap-3">{tools.map(({title,subtitle,icon:Icon,path,tone})=><button key={title} onClick={()=>navigate(path)} className="ms-card-soft ms-pressable min-h-[148px] p-4 text-left"><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${tone}`}><Icon className="h-5 w-5"/></span><h2 className="mt-4 text-sm font-black text-slate-950">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{subtitle}</p></button>)}</div></section><section className="rounded-3xl bg-emerald-50 p-5"><div className="flex items-center gap-2 text-emerald-700"><Sparkles className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Freemium de verdade</span></div><p className="mt-2 text-lg font-black text-emerald-950">Aprender não fica atrás de um paywall.</p><p className="mt-2 text-sm leading-6 text-emerald-900/70">O gratuito mantém aprendizado real. O Pro amplia intensidade, profundidade, simulados e acompanhamento.</p></section></main>}
