import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, BrainCircuit, CheckCircle2, FileText, Sparkles, Target } from 'lucide-react'
import { useEnemStore, type EnemArea } from '@/stores/enem'

type DiagnosticQuestion = { id:string; area:Exclude<EnemArea,'Redação'>; skill:string; text:string; options:string[]; answer:number; difficulty:1|2|3 }
const questions:DiagnosticQuestion[]=[
 {id:'d-l1',area:'Linguagens',skill:'Inferência',text:'Em um texto, uma informação implícita é aquela que:',options:['aparece literalmente','precisa ser deduzida por pistas','está sempre no título','não tem relação com o contexto'],answer:1,difficulty:1},
 {id:'d-l2',area:'Linguagens',skill:'Efeito de sentido',text:'Quando um autor usa ironia, o leitor precisa principalmente:',options:['ignorar o contexto','perceber diferença entre o dito e o sentido pretendido','buscar uma definição no dicionário','contar figuras de linguagem'],answer:1,difficulty:2},
 {id:'d-h1',area:'Humanas',skill:'Fonte histórica',text:'Para interpretar uma fonte histórica, é mais importante considerar:',options:['apenas a data','autoria, contexto e finalidade','somente se é antiga','se concorda com o presente'],answer:1,difficulty:1},
 {id:'d-h2',area:'Humanas',skill:'Cidadania',text:'Uma política pública pode ser entendida como:',options:['ação privada sem impacto coletivo','decisão e ação voltada a problemas públicos','opinião individual','regra informal sem participação estatal'],answer:1,difficulty:2},
 {id:'d-n1',area:'Natureza',skill:'Ecologia',text:'A redução de uma espécie-chave em um ecossistema pode:',options:['não gerar efeito','alterar diferentes relações ecológicas','afetar apenas indivíduos da mesma espécie','impedir toda fotossíntese'],answer:1,difficulty:2},
 {id:'d-n2',area:'Natureza',skill:'Energia',text:'Em uma transformação de energia, é correto afirmar que:',options:['energia surge do nada','energia desaparece completamente','energia pode mudar de forma','toda energia vira matéria'],answer:2,difficulty:1},
 {id:'d-m1',area:'Matemática',skill:'Porcentagem',text:'Um valor de R$ 200 aumenta 10%. Qual é o novo valor?',options:['R$ 210','R$ 215','R$ 220','R$ 240'],answer:2,difficulty:1},
 {id:'d-m2',area:'Matemática',skill:'Proporção',text:'Se 3 cadernos custam R$ 24 no mesmo preço unitário, 5 cadernos custam:',options:['R$ 32','R$ 36','R$ 40','R$ 45'],answer:2,difficulty:2},
]

export function EnemDiagnosticPage(){
 const navigate=useNavigate(); const {profile,saveDiagnostic,recordAttempt}=useEnemStore(); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<number[]>([]); const [writing,setWriting]=useState(''); const [phase,setPhase]=useState<'questions'|'writing'|'result'>('questions')
 const current=questions[index]
 const areaScores=useMemo(()=>{const base:Record<EnemArea,number>={Linguagens:50,Humanas:50,Natureza:50,Matemática:50,Redação:50};(['Linguagens','Humanas','Natureza','Matemática'] as const).forEach(area=>{const items=questions.map((q,i)=>({q,i})).filter(x=>x.q.area===area);const hits=items.filter(x=>answers[x.i]===x.q.answer).length;base[area]=items.length?Math.round(30+(hits/items.length)*70):50});const words=writing.trim().split(/\s+/).filter(Boolean).length;const hasBecause=/porque|pois|portanto|assim|logo|consequentemente/i.test(writing);base.Redação=Math.max(30,Math.min(85,35+Math.min(30,words)+ (hasBecause?15:0)));return base},[answers,writing])
 const accuracy=answers.length?Math.round(answers.filter((answer,i)=>answer===questions[i].answer).length/answers.length*100):0
 const answer=(option:number)=>{const next=[...answers,option];setAnswers(next);recordAttempt({questionId:current.id,area:current.area,skill:current.skill,correct:option===current.answer,difficulty:current.difficulty});if(index===questions.length-1)setPhase('writing');else setIndex(index+1)}
 const finish=()=>{saveDiagnostic({questionCount:questions.length,accuracy,areaScores,writingSample:writing,writingSignal:areaScores.Redação});setPhase('result')}
 const weakest=(Object.entries(areaScores) as [EnemArea,number][]).sort((a,b)=>a[1]-b[1])[0]

 return <main className="ms-screen space-y-4 py-4">
  <section className="rounded-[32px] bg-gradient-to-br from-cyan-600 via-indigo-700 to-violet-700 p-5 text-white shadow-xl shadow-indigo-100"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-100">Diagnóstico inicial</p><h1 className="mt-2 text-2xl font-black">Poucos sinais. Um mapa melhor.</h1></div><BrainCircuit className="h-8 w-8"/></div><p className="mt-3 text-sm leading-6 text-white/80">São 8 questões curtas e 1 microatividade de escrita. Não é prova nem nota oficial.</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-white transition-all" style={{width:`${phase==='questions'?Math.round((index/questions.length)*80):phase==='writing'?90:100}%`}}/></div></section>

  {phase==='questions'&&<section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-black text-indigo-700">{current.area}</span><span className="text-xs font-bold text-slate-400">{index+1}/{questions.length}</span></div><h2 className="mt-4 text-lg font-black leading-7">{current.text}</h2><div className="mt-4 space-y-2">{current.options.map((option,i)=><button key={option} onClick={()=>answer(i)} className="flex w-full items-center gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 text-left text-sm font-bold text-slate-800 active:scale-[.99]"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-white text-xs font-black">{String.fromCharCode(65+i)}</span><span>{option}</span></button>)}</div></section>}

  {phase==='writing'&&<section className="space-y-3"><div className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-fuchsia-700"><FileText className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Microatividade de escrita</span></div><h2 className="mt-2 text-lg font-black">Em 3–5 frases, responda:</h2><p className="mt-2 text-sm leading-6 text-slate-600">“A tecnologia aproxima ou afasta as pessoas?” Defenda uma posição e explique pelo menos um motivo.</p><textarea value={writing} onChange={(e)=>setWriting(e.target.value)} rows={7} placeholder="Escreva com suas palavras..." className="mt-4 w-full resize-none rounded-2xl bg-slate-50 p-4 text-sm leading-6 outline-none ring-indigo-200 focus:ring-2"/><p className="mt-2 text-xs text-slate-400">Não buscamos perfeição. Queremos um primeiro sinal de clareza, posição e justificativa.</p></div><button disabled={writing.trim().length<30} onClick={finish} className="w-full rounded-2xl bg-fuchsia-600 py-4 text-sm font-black text-white disabled:opacity-40">Gerar meu primeiro mapa</button></section>}

  {phase==='result'&&<section className="space-y-4"><div className="rounded-3xl bg-emerald-50 p-5"><div className="flex items-center gap-2 text-emerald-700"><CheckCircle2 className="h-5 w-5"/><span className="text-xs font-black uppercase tracking-wider">Diagnóstico concluído</span></div><h2 className="mt-2 text-2xl font-black text-emerald-950">Seu primeiro mapa nasceu.</h2><p className="mt-2 text-sm leading-6 text-emerald-900/70">Agora a autopercepção começa a ser substituída por evidências reais. Quanto mais você pratica, melhor o mapa fica.</p></div><div className="grid grid-cols-2 gap-3">{(Object.entries(areaScores) as [EnemArea,number][]).map(([area,score])=><div key={area} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-xs font-bold text-slate-400">{area}</p><p className="mt-1 text-2xl font-black">{score}</p><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${score}%`}}/></div></div>)}</div><div className="rounded-3xl bg-amber-50 p-5"><div className="flex items-center gap-2 text-amber-700"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Primeiro foco</span></div><h3 className="mt-2 text-xl font-black text-amber-950">{weakest[0]}</h3><p className="mt-1 text-sm text-amber-900/70">É o menor sinal inicial. Isso não é rótulo: é só uma pista para escolher o próximo treino.</p></div><button onClick={()=>navigate('/enem/hoje')} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white">Ir para meu primeiro dia <ArrowRight className="h-4 w-4"/></button>{profile?.targetCourse&&<p className="text-center text-xs text-slate-400">Plano orientado para {profile.targetCourse} · meta {profile.targetScore}</p>}</section>}

  <section className="rounded-3xl bg-slate-950 p-4 text-white"><div className="flex gap-3"><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-violet-300"/><p className="text-xs leading-5 text-slate-400">O diagnóstico serve para personalização educacional. Ele não estima nota oficial do ENEM nem substitui avaliação pedagógica formal.</p></div></section>
 </main>
}
