import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { BookOpenCheck, ChevronRight, Compass, FileText, Sparkles, Target } from 'lucide-react'
import { useEnemStore, type EnemArea } from '@/stores/enem'
import { useWritingStore } from '@/stores/writing'
import { buildEnemSkillMap, findPrioritySkill } from '@/lib/enemSkillMap'

const tones:Record<EnemArea,string>={Linguagens:'bg-fuchsia-500',Humanas:'bg-amber-500',Natureza:'bg-emerald-500',Matemática:'bg-cyan-500',Redação:'bg-violet-500'}

export function EnemMapPage(){
 const navigate=useNavigate(); const {attempts}=useEnemStore(); const {projects}=useWritingStore()
 const areas=useMemo(()=>buildEnemSkillMap(attempts,projects),[attempts,projects]); const priority=useMemo(()=>findPrioritySkill(areas),[areas]); const focusArea=areas.find(a=>a.area===priority.area)!
 return <main className="ms-screen space-y-4 py-4">
  <section className="relative overflow-hidden rounded-[30px] bg-[#17152f] p-5 text-white"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-cyan-400/20 blur-2xl"/><div className="relative flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Meu mapa ENEM</p><h1 className="mt-2 text-2xl font-black">Agora o mapa enxerga habilidades.</h1><p className="mt-2 text-sm leading-6 text-white/70">Não basta saber que Matemática precisa de atenção. Queremos descobrir exatamente qual habilidade merece o próximo treino.</p></div><Compass className="h-8 w-8 text-cyan-300"/></div></section>

  <section className="grid grid-cols-2 gap-3"><div className="rounded-3xl bg-amber-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-amber-700">Prioridade atual</p><p className="mt-2 text-lg font-black text-amber-950">{priority.skill}</p><p className="mt-1 text-xs leading-5 text-amber-900/70">{priority.area} · sinal {priority.score}/100</p></div><div className="rounded-3xl bg-emerald-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Evidências</p><p className="mt-2 text-2xl font-black text-emerald-950">{areas.reduce((n,a)=>n+a.evidenceCount,0)}</p><p className="mt-1 text-xs leading-5 text-emerald-900/70">atividades alimentando o mapa.</p></div></section>

  <section><div className="mb-3"><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Mapa granular</p><h2 className="text-xl font-black">Área → habilidade → próximo passo</h2></div><div className="space-y-3">{areas.map(area=><article key={area.area} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-black">{area.area}</p><p className="mt-0.5 text-[10px] font-bold text-slate-400">{area.evidenceCount} evidências</p></div><p className="text-lg font-black text-slate-700">{area.score}</p></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${tones[area.area]}`} style={{width:`${area.score}%`}}/></div><div className="mt-4 space-y-2">{area.skills.map(skill=><div key={skill.skill} className={`rounded-2xl p-3 ${skill.skill===priority.skill&&skill.area===priority.area?'bg-amber-50':'bg-slate-50'}`}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black text-slate-800">{skill.skill}</p><p className="mt-0.5 text-[10px] font-bold text-slate-400">{skill.evidenceCount?`${skill.evidenceCount} evidência${skill.evidenceCount>1?'s':''}`:'baseline inicial'}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${skill.score<50?'bg-rose-100 text-rose-700':skill.score<70?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{skill.score}</span></div></div>)}</div></article>)}</div></section>

  <section className="rounded-3xl bg-indigo-50 p-5"><div className="flex items-center gap-2 text-indigo-700"><Sparkles className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Próximo passo</span></div><h2 className="mt-2 text-lg font-black">Treinar {priority.skill}</h2><p className="mt-1 text-sm leading-6 text-indigo-900/70">Hoje a menor habilidade observada está em {focusArea.area}. O Meu Dia ENEM pode usar esse sinal diretamente, sem reduzir você a uma média por matéria.</p><button onClick={()=>navigate('/enem/hoje')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-700 py-3.5 text-sm font-black text-white">Abrir meu plano <ChevronRight className="h-4 w-4"/></button></section>

  <section className="grid grid-cols-2 gap-3"><button onClick={()=>navigate('/enem/questoes')} className="rounded-3xl bg-white p-4 text-left shadow-sm"><BookOpenCheck className="h-5 w-5 text-cyan-600"/><p className="mt-3 text-sm font-black">Questões</p><p className="mt-1 text-xs text-slate-500">{attempts.length} respostas registradas.</p></button><button onClick={()=>navigate('/enem/redacao/dna')} className="rounded-3xl bg-white p-4 text-left shadow-sm"><FileText className="h-5 w-5 text-violet-600"/><p className="mt-3 text-sm font-black">DNA da escrita</p><p className="mt-1 text-xs text-slate-500">{projects.filter(p=>p.versions.length).length} textos com sinal.</p></button></section>

  <section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-cyan-300"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Regra do motor</span></div><p className="mt-2 text-sm leading-6 text-slate-400">Habilidades com evidência real têm prioridade sobre baselines. O mapa é provisório por design: cada nova resposta pode reforçar, enfraquecer ou substituir uma hipótese anterior.</p></section>
 </main>
}
