import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { BookOpenCheck, Check, ChevronRight, FileText, RefreshCw, Sparkles, Target } from 'lucide-react'
import { useWritingStore } from '@/stores/writing'
import { useEnemStore, type EnemArea } from '@/stores/enem'
import { buildEnemSkillMap, findPrioritySkill } from '@/lib/enemSkillMap'

export function EnemTodayPage(){
 const navigate=useNavigate(); const {projects}=useWritingStore(); const {profile,diagnostic,attempts,dailyCompleted,toggleDailyStep}=useEnemStore()
 const today=new Date().toISOString().slice(0,10)
 const focus=useMemo(()=>{
   const map=buildEnemSkillMap(attempts,projects); let priority=findPrioritySkill(map)
   if(!map.some(area=>area.evidenceCount>0)&&profile){const weakest=(Object.entries(profile.confidence) as [EnemArea,number][]).sort((a,b)=>a[1]-b[1])[0][0];const area=map.find(item=>item.area===weakest);if(area)priority={...area.skills[0],score:profile.confidence[weakest]*20}}
   return {name:priority.area,skill:priority.skill,value:priority.score,evidenceCount:priority.evidenceCount,path:priority.area==='Redação'?'/enem/redacao/coach':'/enem/questoes'}
 },[attempts,projects,profile])
 const plan=useMemo(()=>[
  {minutes:8,label:'Aprender',title:`Entenda ${focus.skill}`,text:`Hoje o conceito central é ${focus.skill}. Tente explicá-lo com suas próprias palavras antes de praticar.`,path:focus.path,icon:Sparkles},
  {minutes:7,label:'Praticar',title:`Treino de ${focus.skill}`,text:`Pratique a habilidade, não apenas a matéria ${focus.name}. Cada resposta atualiza esse sinal.`,path:focus.path,icon:BookOpenCheck},
  {minutes:5,label:'Revisar',title:`Recupere ${focus.skill} sem consultar`,text:'Tente reconstruir o raciocínio antes de rever. Recuperação ativa fortalece memória e compreensão.',path:'/enem/mapa',icon:RefreshCw},
  {minutes:5,label:'Escrever',title:'Transforme raciocínio em palavras',text:focus.name==='Redação'?`Aplique ${focus.skill} em uma nova tentativa.`:'Explique o que aprendeu como se estivesse ensinando outra pessoa.',path:focus.name==='Redação'?'/enem/redacao/coach':'/enem/redacao/escrever',icon:FileText},
 ],[focus])
 const stepKey=(i:number)=>`${today}:${focus.name}:${focus.skill}:${i}`; const total=plan.reduce((n,p)=>n+p.minutes,0); const completed=plan.reduce((n,p,i)=>n+(dailyCompleted.includes(stepKey(i))?p.minutes:0),0)
 return <main className="ms-screen space-y-4 py-4">
  <section className="relative overflow-hidden rounded-[32px] bg-gradient-to-br from-indigo-700 via-violet-700 to-fuchsia-600 p-5 text-white shadow-xl shadow-violet-100"><div className="absolute -right-14 -top-16 h-48 w-48 rounded-full bg-white/10 blur-2xl"/><div className="relative"><p className="text-xs font-black uppercase tracking-[.18em] text-violet-100">Meu Dia ENEM</p><h1 className="mt-2 text-3xl font-black">Hoje, só o próximo passo.</h1><p className="mt-2 text-sm leading-6 text-white/80">{profile?`Meta ${profile.targetScore}${profile.targetCourse?` · ${profile.targetCourse}`:''}. `:''}Agora o plano escolhe uma habilidade específica, não apenas uma matéria.</p><div className="mt-5 flex items-end justify-between"><div><p className="text-3xl font-black">{completed}/{total}</p><p className="text-xs font-bold text-white/70">minutos concluídos hoje</p></div><div className="max-w-[48%] rounded-2xl bg-white/15 px-3 py-2 text-right"><p className="text-[10px] font-black uppercase tracking-wider text-white/70">foco de hoje</p><p className="text-sm font-black">{focus.skill}</p><p className="text-[10px] font-bold text-white/60">{focus.name}</p></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-white transition-all" style={{width:`${Math.round(completed/total*100)}%`}}/></div></div></section>
  {!profile&&<section className="rounded-3xl border border-violet-100 bg-violet-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-violet-700">Personalize seu ENEM</p><h2 className="mt-2 font-black text-violet-950">Seu plano ainda está usando um ponto de partida neutro.</h2><button onClick={()=>navigate('/enem/configurar')} className="mt-3 rounded-2xl bg-violet-700 px-4 py-3 text-sm font-black text-white">Montar meu plano →</button></section>}
  {profile&&!diagnostic&&<section className="rounded-3xl border border-cyan-100 bg-cyan-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-cyan-700">Falta um passo curto</p><h2 className="mt-2 font-black text-cyan-950">Troque autopercepção por evidências iniciais.</h2><p className="mt-1 text-sm leading-6 text-cyan-900/70">O diagnóstico adaptativo cria os primeiros sinais por habilidade.</p><button onClick={()=>navigate('/enem/diagnostico')} className="mt-3 rounded-2xl bg-cyan-700 px-4 py-3 text-sm font-black text-white">Fazer diagnóstico →</button></section>}
  <section className="rounded-3xl bg-amber-50 p-5"><div className="flex items-center gap-2 text-amber-700"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Por que este foco?</span></div><h2 className="mt-2 text-lg font-black text-amber-950">{focus.skill} · {focus.value}/100</h2><p className="mt-1 text-sm leading-6 text-amber-900/70">{focus.evidenceCount?`Há ${focus.evidenceCount} evidência${focus.evidenceCount>1?'s':''} diretamente ligada${focus.evidenceCount>1?'s':''} a esta habilidade.`:'Ainda é um baseline inicial. Assim que você praticar, o sinal passa a refletir desempenho real.'}</p><button onClick={()=>navigate('/enem/mapa')} className="mt-3 text-xs font-black text-amber-800">Ver mapa completo →</button></section>
  <section className="space-y-3">{plan.map((item,i)=>{const Icon=item.icon;const key=stepKey(i);const finished=dailyCompleted.includes(key);return <article key={item.label} className={`rounded-3xl border p-4 shadow-sm ${finished?'border-emerald-100 bg-emerald-50':'border-slate-100 bg-white'}`}><div className="flex items-start gap-3"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${finished?'bg-emerald-600 text-white':'bg-indigo-50 text-indigo-700'}`}>{finished?<Check className="h-5 w-5"/>:<Icon className="h-5 w-5"/>}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-xs font-black uppercase tracking-wider text-slate-400">{item.label} · {item.minutes} min</p>{finished&&<span className="text-[10px] font-black text-emerald-700">FEITO</span>}</div><h2 className="mt-1 text-base font-black">{item.title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{item.text}</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>navigate(item.path)} className="rounded-xl bg-slate-950 py-2.5 text-xs font-black text-white">Abrir <ChevronRight className="ml-1 inline h-3 w-3"/></button><button onClick={()=>toggleDailyStep(key)} className="rounded-xl bg-slate-100 py-2.5 text-xs font-black text-slate-700">{finished?'Desmarcar':'Concluir etapa'}</button></div></div></div></article>})}</section>
  <section className="rounded-3xl bg-slate-950 p-5 text-white"><p className="text-xs font-black uppercase tracking-wider text-violet-300">Princípio MindSteps</p><p className="mt-2 text-lg font-black">A matéria é grande. O próximo passo não precisa ser.</p><p className="mt-2 text-sm leading-6 text-slate-400">O sistema quebra áreas amplas em habilidades observáveis para transformar diagnóstico em ação concreta e mensurável.</p></section>
 </main>
}
