import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, CheckCircle2, ChevronRight, Lightbulb, RotateCcw, Target, XCircle } from 'lucide-react'
import { useEnemStore, type EnemArea } from '@/stores/enem'
import { useWritingStore } from '@/stores/writing'
import { buildEnemSkillMap } from '@/lib/enemSkillMap'

type Question={id:string;area:Exclude<EnemArea,'Redação'>;skill:string;text:string;options:string[];answer:number;explanation:string;difficulty:1|2|3}
const bank:Question[]=[
{id:'p-l-inf-1',area:'Linguagens',skill:'Inferência',text:'Quando um texto sugere uma ideia sem afirmá-la diretamente, o leitor precisa:',options:['copiar uma frase','inferir a partir de pistas','contar palavras','memorizar o autor'],answer:1,explanation:'Inferir é construir uma conclusão a partir de pistas explícitas e implícitas.',difficulty:1},
{id:'p-l-inf-3',area:'Linguagens',skill:'Inferência',text:'Uma campanha afirma “Seu clique também escolhe o mundo que você vê”. A frase sugere que:',options:['algoritmos não influenciam conteúdo','as escolhas digitais ajudam a moldar o que aparece ao usuário','todo clique é público','a internet mostra o mesmo conteúdo a todos'],answer:1,explanation:'A ideia implícita é que interações do usuário influenciam recomendações e exposição a conteúdos.',difficulty:3},
{id:'p-l-efe-1',area:'Linguagens',skill:'Efeito de sentido',text:'Em “Que ótimo, mais duas horas no trânsito!”, dito após um engarrafamento, o efeito principal é:',options:['elogio literal','ironia','descrição neutra','dúvida'],answer:1,explanation:'O contraste entre “ótimo” e a situação negativa produz ironia.',difficulty:1},
{id:'p-l-efe-3',area:'Linguagens',skill:'Efeito de sentido',text:'A repetição de uma mesma expressão ao início de vários períodos pode produzir principalmente:',options:['ênfase e ritmo','apagamento do tema','ausência de coesão','neutralidade absoluta'],answer:0,explanation:'A repetição deliberada pode reforçar uma ideia e criar ritmo argumentativo.',difficulty:3},
{id:'p-l-crit-1',area:'Linguagens',skill:'Leitura crítica',text:'Ao comparar duas notícias sobre o mesmo fato, uma leitura crítica deve observar:',options:['só o tamanho','fontes, recortes e evidências','apenas o título','qual foi publicada primeiro'],answer:1,explanation:'Leitura crítica compara fontes, enquadramentos e evidências usadas para sustentar afirmações.',difficulty:1},
{id:'p-l-crit-3',area:'Linguagens',skill:'Leitura crítica',text:'Um texto apresenta apenas exemplos favoráveis à própria tese. O leitor crítico deve perguntar:',options:['se a fonte usa palavras difíceis','quais evidências ou perspectivas relevantes ficaram de fora','quantas linhas há','se o autor usa subtítulos'],answer:1,explanation:'Investigar omissões e contraevidências ajuda a avaliar a força de uma argumentação.',difficulty:3},
{id:'p-h-fonte-1',area:'Humanas',skill:'Fonte histórica',text:'Para interpretar uma fonte histórica, é importante considerar:',options:['apenas a data','autoria, contexto e finalidade','somente se é antiga','se concorda com o presente'],answer:1,explanation:'Fontes ganham sentido quando analisadas no contexto em que foram produzidas.',difficulty:1},
{id:'p-h-fonte-3',area:'Humanas',skill:'Fonte histórica',text:'Um cartaz político produzido durante uma eleição é melhor analisado como:',options:['registro neutro da realidade','fonte situada, com intenção e público específicos','prova definitiva de todos os fatos','texto sem contexto histórico'],answer:1,explanation:'Toda fonte é situada; intenção, público e contexto importam para interpretá-la.',difficulty:3},
{id:'p-h-cid-1',area:'Humanas',skill:'Cidadania',text:'Uma política pública é:',options:['opinião individual','ação voltada a problemas coletivos','regra privada sem impacto social','costume familiar'],answer:1,explanation:'Políticas públicas organizam ações do poder público diante de necessidades coletivas.',difficulty:1},
{id:'p-h-cid-3',area:'Humanas',skill:'Cidadania',text:'Avaliar uma política pública exige observar principalmente:',options:['apenas sua propaganda','objetivos, implementação, alcance e resultados','somente quem a anunciou','a quantidade de páginas da lei'],answer:1,explanation:'A avaliação precisa considerar desenho, execução e efeitos produzidos.',difficulty:3},
{id:'p-h-rel-1',area:'Humanas',skill:'Relações sociais',text:'Ao estudar desigualdade social, é útil analisar:',options:['só casos individuais','indicadores e processos históricos','apenas preferências pessoais','somente clima'],answer:1,explanation:'Desigualdades são compreendidas melhor com dados e processos históricos e sociais.',difficulty:1},
{id:'p-h-rel-3',area:'Humanas',skill:'Relações sociais',text:'Dizer que oportunidades dependem apenas de esforço individual ignora principalmente:',options:['diferenças de acesso a recursos e condições sociais','o calendário escolar','o clima regional','a existência de escolhas pessoais'],answer:0,explanation:'Esforço importa, mas condições estruturais também influenciam oportunidades.',difficulty:3},
{id:'p-n-eco-1',area:'Natureza',skill:'Ecologia',text:'A retirada de um predador de topo pode provocar:',options:['nenhuma alteração','desequilíbrios em vários níveis tróficos','fim imediato do ecossistema','apenas redução de plantas'],answer:1,explanation:'Predadores de topo regulam populações e sua ausência pode gerar efeitos em cascata.',difficulty:1},
{id:'p-n-eco-3',area:'Natureza',skill:'Ecologia',text:'Se uma população herbívora cresce muito após a redução de predadores, uma consequência provável é:',options:['menor pressão sobre plantas','maior consumo de produtores','aumento automático de biodiversidade','fim da competição'],answer:1,explanation:'Mais herbívoros podem aumentar a pressão de consumo sobre produtores.',difficulty:3},
{id:'p-n-ene-1',area:'Natureza',skill:'Energia',text:'Em uma transformação de energia:',options:['energia surge do nada','energia pode mudar de forma','energia sempre vira matéria','energia desaparece totalmente'],answer:1,explanation:'A energia pode ser transformada entre diferentes formas.',difficulty:1},
{id:'p-n-ene-3',area:'Natureza',skill:'Energia',text:'Uma lâmpada converte energia elétrica principalmente em:',options:['energia luminosa e térmica','massa e som apenas','energia química apenas','matéria escura'],answer:0,explanation:'Parte vira luz e parte é dissipada como calor.',difficulty:3},
{id:'p-n-evi-1',area:'Natureza',skill:'Evidência científica',text:'Uma hipótese científica ganha suporte quando:',options:['é repetida muitas vezes','suas previsões são compatíveis com evidências','é defendida por uma pessoa famosa','não pode ser testada'],answer:1,explanation:'Hipóteses científicas precisam ser confrontadas com observações e testes.',difficulty:1},
{id:'p-n-evi-3',area:'Natureza',skill:'Evidência científica',text:'Dois estudos chegam a resultados diferentes. O melhor próximo passo é:',options:['escolher o resultado preferido','comparar métodos, amostras e replicações','descartar ambos automaticamente','votar nas conclusões'],answer:1,explanation:'Divergências pedem análise de método, qualidade da evidência e possibilidade de replicação.',difficulty:3},
{id:'p-m-por-1',area:'Matemática',skill:'Porcentagem',text:'Uma loja dá 20% de desconto em R$ 150. O preço final é:',options:['R$ 100','R$ 110','R$ 120','R$ 130'],answer:2,explanation:'20% de 150 = 30; 150 − 30 = 120.',difficulty:1},
{id:'p-m-por-3',area:'Matemática',skill:'Porcentagem',text:'Um preço sobe 20% e depois cai 20%. Em relação ao preço inicial, o resultado é:',options:['igual','4% menor','4% maior','20% menor'],answer:1,explanation:'1,20 × 0,80 = 0,96; portanto o valor final é 4% menor.',difficulty:3},
{id:'p-m-pro-1',area:'Matemática',skill:'Proporção',text:'Se 3 cadernos custam R$ 24, 5 custam:',options:['R$ 32','R$ 36','R$ 40','R$ 45'],answer:2,explanation:'Cada caderno custa R$ 8; 5 × 8 = R$ 40.',difficulty:1},
{id:'p-m-pro-3',area:'Matemática',skill:'Proporção',text:'Uma receita para 4 pessoas usa 300 g de farinha. Para 10 pessoas, mantendo a proporção, são necessários:',options:['600 g','700 g','750 g','900 g'],answer:2,explanation:'300/4 = 75 g por pessoa; 75 × 10 = 750 g.',difficulty:3},
{id:'p-m-mod-1',area:'Matemática',skill:'Modelagem',text:'Uma corrida cobra R$ 6 fixos mais R$ 2 por km. Para 8 km, o total é:',options:['R$ 16','R$ 20','R$ 22','R$ 28'],answer:2,explanation:'6 + 2×8 = 22.',difficulty:1},
{id:'p-m-mod-3',area:'Matemática',skill:'Modelagem',text:'Um plano custa R$ 30 fixos mais R$ 5 por GB extra. Uma conta de R$ 55 representa quantos GB extras?',options:['3','4','5','6'],answer:2,explanation:'55 − 30 = 25; 25/5 = 5 GB.',difficulty:3},
]

export function EnemQuestionsPage(){
 const navigate=useNavigate(); const {attempts,recordAttempt,resetPractice}=useEnemStore(); const {projects}=useWritingStore(); const [selected,setSelected]=useState<number|null>(null); const [sessionDifficulty,setSessionDifficulty]=useState<1|2|3>(2); const [served,setServed]=useState<string[]>([])
 const map=useMemo(()=>buildEnemSkillMap(attempts,projects),[attempts,projects]); const priority=useMemo(()=>{const nonWriting=map.filter(a=>a.area!=='Redação').flatMap(a=>a.skills);const evidenced=nonWriting.filter(s=>s.evidenceCount>0);return [...(evidenced.length?evidenced:nonWriting)].sort((a,b)=>a.score-b.score||b.evidenceCount-a.evidenceCount)[0]},[map])
 const candidates=useMemo(()=>bank.filter(q=>q.area===priority.area&&q.skill===priority.skill),[priority]); const q=useMemo(()=>{const unused=candidates.filter(x=>!served.includes(x.id));const pool=unused.length?unused:candidates;return [...pool].sort((a,b)=>Math.abs(a.difficulty-sessionDifficulty)-Math.abs(b.difficulty-sessionDifficulty))[0]||bank[0]},[candidates,served,sessionDifficulty]); const answered=selected!==null
 const recent=attempts.filter(a=>!a.questionId.startsWith('d')).slice(-30); const accuracy=recent.length?Math.round(recent.filter(a=>a.correct).length/recent.length*100):0
 const choose=(i:number)=>{if(answered)return;setSelected(i);const correct=i===q.answer;recordAttempt({questionId:q.id,area:q.area,skill:q.skill,correct,difficulty:q.difficulty});setSessionDifficulty(d=>correct?Math.min(3,d+1) as 1|2|3:Math.max(1,d-1) as 1|2|3)}
 const next=()=>{setServed(s=>[...s,q.id]);setSelected(null)}
 return <main className="ms-screen space-y-4 py-4">
  <section className="rounded-[30px] bg-gradient-to-br from-cyan-600 via-blue-700 to-indigo-800 p-5 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-100">Prática adaptativa</p><h1 className="mt-2 text-2xl font-black">Treine exatamente onde há espaço para crescer.</h1><p className="mt-2 text-sm leading-6 text-white/75">O mapa escolhe a habilidade. Sua resposta ajusta a dificuldade da próxima questão.</p></section>
  <section className="rounded-3xl bg-violet-50 p-5"><div className="flex items-center gap-2 text-violet-700"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Foco desta sessão</span></div><h2 className="mt-2 text-xl font-black text-violet-950">{priority.skill}</h2><p className="mt-1 text-sm text-violet-900/70">{priority.area} · sinal {priority.score}/100 · {priority.evidenceCount} evidências</p></section>
  <section className="grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-white p-3 shadow-sm"><p className="text-xl font-black">{recent.length}</p><p className="text-[10px] font-bold text-slate-400">práticas</p></div><div className="rounded-2xl bg-white p-3 shadow-sm"><p className="text-xl font-black">{accuracy}%</p><p className="text-[10px] font-bold text-slate-400">acerto recente</p></div><div className="rounded-2xl bg-white p-3 shadow-sm"><p className="text-xl font-black">N{q.difficulty}</p><p className="text-[10px] font-bold text-slate-400">dificuldade</p></div></section>
  <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-black text-cyan-700">{q.area}</span><span className="text-xs font-bold text-slate-400">{q.skill}</span></div><h2 className="mt-4 text-lg font-black leading-7">{q.text}</h2><div className="mt-4 space-y-2">{q.options.map((o,i)=>{const isCorrect=i===q.answer,isSelected=i===selected;return <button key={o} onClick={()=>choose(i)} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left text-sm font-bold transition ${answered&&isCorrect?'border-emerald-300 bg-emerald-50 text-emerald-900':answered&&isSelected&&!isCorrect?'border-rose-300 bg-rose-50 text-rose-900':'border-slate-100 bg-slate-50 text-slate-800'}`}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-white text-xs font-black">{String.fromCharCode(65+i)}</span><span className="flex-1">{o}</span>{answered&&isCorrect&&<CheckCircle2 className="h-5 w-5 text-emerald-600"/>}{answered&&isSelected&&!isCorrect&&<XCircle className="h-5 w-5 text-rose-600"/>}</button>})}</div></section>
  {answered&&<section className={`rounded-3xl p-5 ${selected===q.answer?'bg-emerald-50':'bg-amber-50'}`}><div className="flex items-center gap-2"><Lightbulb className="h-5 w-5"/><p className="text-sm font-black">Entenda o raciocínio</p></div><p className="mt-2 text-sm leading-6 opacity-75">{q.explanation}</p><p className="mt-3 text-xs font-bold opacity-60">{selected===q.answer?'Acertou: a próxima tende a ficar mais desafiadora.':'Errou: a próxima tende a reduzir a dificuldade antes de subir novamente.'}</p><button onClick={next} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white">Próxima adaptativa <ArrowRight className="h-4 w-4"/></button></section>}
  <div className="grid grid-cols-2 gap-3"><button onClick={()=>{resetPractice();setSelected(null);setServed([]);setSessionDifficulty(2)}} className="flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white py-3 text-sm font-black"><RotateCcw className="h-4 w-4"/>Zerar prática</button><button onClick={()=>navigate('/enem/mapa')} className="flex items-center justify-center gap-2 rounded-2xl bg-indigo-100 py-3 text-sm font-black text-indigo-800">Ver meu mapa <ChevronRight className="h-4 w-4"/></button></div>
 </main>
}
