import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertCircle, BookOpenCheck, ChevronRight, RotateCcw, Sparkles, Target } from 'lucide-react'
import { useEnemStore, type EnemArea } from '@/stores/enem'

type ErrorGroup={area:EnemArea;skill:string;errors:number;attempts:number;last:string;recovery:number}

export function EnemErrorsPage(){
 const navigate=useNavigate();const {attempts}=useEnemStore()
 const groups=useMemo(()=>{
  const map=new Map<string,ErrorGroup>()
  attempts.forEach(a=>{const key=`${a.area}:${a.skill}`;const current=map.get(key)||{area:a.area,skill:a.skill,errors:0,attempts:0,last:a.createdAt,recovery:0};current.attempts++;if(!a.correct)current.errors++;current.last=a.createdAt;map.set(key,current)})
  const list=[...map.values()].map(g=>({...g,recovery:Math.max(0,Math.round((1-g.errors/Math.max(1,g.attempts))*100))}))
  return list.filter(g=>g.errors>0).sort((a,b)=>b.errors-a.errors||a.recovery-b.recovery)
 },[attempts])
 const totalErrors=groups.reduce((n,g)=>n+g.errors,0);const priority=groups[0]
 return <main className="ms-screen space-y-4 py-4">
  <section className="relative overflow-hidden rounded-[32px] bg-gradient-to-br from-rose-600 via-fuchsia-700 to-indigo-800 p-5 text-white"><div className="absolute -right-14 -top-16 h-48 w-48 rounded-full bg-white/10 blur-2xl"/><div className="relative"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-rose-100">Caderno de erros</p><h1 className="mt-2 text-2xl font-black">Erro vira pista, não sentença.</h1></div><RotateCcw className="h-8 w-8"/></div><p className="mt-3 text-sm leading-6 text-white/80">O MindSteps agrupa padrões de erro para transformar dificuldade repetida em revisão direcionada.</p></div></section>
  <section className="grid grid-cols-2 gap-3"><div className="rounded-3xl bg-rose-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-rose-700">Erros registrados</p><p className="mt-2 text-3xl font-black text-rose-950">{totalErrors}</p><p className="mt-1 text-xs text-rose-900/60">em questões e simulados</p></div><div className="rounded-3xl bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-indigo-700">Habilidades</p><p className="mt-2 text-3xl font-black text-indigo-950">{groups.length}</p><p className="mt-1 text-xs text-indigo-900/60">com algo para recuperar</p></div></section>
  {priority?<section className="rounded-3xl bg-amber-50 p-5"><div className="flex items-center gap-2 text-amber-700"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Prioridade de recuperação</span></div><h2 className="mt-2 text-xl font-black text-amber-950">{priority.skill}</h2><p className="mt-1 text-sm leading-6 text-amber-900/70">{priority.area} · {priority.errors} erro{priority.errors>1?'s':''} em {priority.attempts} tentativa{priority.attempts>1?'s':''}. Melhor revisar o raciocínio antes de acumular novas questões.</p><button onClick={()=>navigate('/enem/questoes')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-amber-700 py-3.5 text-sm font-black text-white">Treinar habilidade <ChevronRight className="h-4 w-4"/></button></section>:<section className="rounded-3xl bg-emerald-50 p-5"><Sparkles className="h-5 w-5 text-emerald-700"/><h2 className="mt-3 text-xl font-black text-emerald-950">Seu caderno ainda está vazio.</h2><p className="mt-2 text-sm leading-6 text-emerald-900/70">Quando você errar uma questão, o erro aparece aqui como oportunidade de revisão. Comece sem medo de errar.</p><button onClick={()=>navigate('/enem/questoes')} className="mt-4 w-full rounded-2xl bg-emerald-700 py-3.5 text-sm font-black text-white">Responder questões</button></section>}
  {groups.length>0&&<section><div className="mb-3"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Fila de recuperação</p><h2 className="text-xl font-black">Onde vale voltar</h2></div><div className="space-y-3">{groups.map(g=><article key={`${g.area}:${g.skill}`} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-rose-50 text-rose-600"><AlertCircle className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-black">{g.skill}</p><p className="text-xs text-slate-400">{g.area}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">{g.recovery}/100</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${g.recovery}%`}}/></div><div className="mt-2 flex items-center justify-between text-[10px] font-bold text-slate-400"><span>{g.errors} erro{g.errors>1?'s':''}</span><span>{g.attempts} tentativa{g.attempts>1?'s':''}</span></div></div></div></article>)}</div></section>}
  <section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-cyan-300"><BookOpenCheck className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Princípio de revisão</span></div><p className="mt-2 text-sm leading-6 text-slate-400">Não basta repetir até acertar. O objetivo é entender o motivo do erro, reconhecer o padrão e conseguir resolver uma variação depois.</p></section>
 </main>
}
