import { useNavigate } from 'react-router-dom'
import { ArrowRight, BrainCircuit, Clock3, Flag, RefreshCw, Sparkles, Target } from 'lucide-react'
import { useEnemStore } from '@/stores/enem'
import { buildStrategyInsights } from '@/lib/enemStrategyCoach'

const tone={amber:'bg-amber-50 text-amber-950',rose:'bg-rose-50 text-rose-950',emerald:'bg-emerald-50 text-emerald-950',indigo:'bg-indigo-50 text-indigo-950'}
export function EnemStrategyCoachPage(){const navigate=useNavigate();const {simulations}=useEnemStore();const insights=buildStrategyInsights(simulations);const recent=simulations.slice(0,5);const avg=recent.length?Math.round(recent.reduce((n,s)=>n+(s.strategyScore??0),0)/recent.length):0;return <main className="ms-screen space-y-4 py-4">
<section className="rounded-[32px] bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-800 p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-200">Coach de Estratégia</p><h1 className="mt-2 text-2xl font-black">Aprenda a fazer prova.</h1></div><BrainCircuit className="h-8 w-8 text-violet-200"/></div><p className="mt-3 text-sm leading-6 text-white/75">Conhecimento importa. Mas tempo, dúvida, revisão e decisão também podem ser treinados.</p>{recent.length>0&&<div className="mt-4 rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold text-white/60">Strategy Score médio · últimas {recent.length}</p><p className="mt-1 text-3xl font-black">{avg}/100</p></div>}</section>
{!recent.length?<section className="rounded-3xl bg-white p-5 shadow-sm"><Target className="h-6 w-6 text-indigo-600"/><h2 className="mt-3 text-xl font-black">Primeiro precisamos observar você em prova.</h2><p className="mt-2 text-sm leading-6 text-slate-500">Faça um simulado curto. Vamos registrar respostas, tempo, marcações, pulos e revisão para gerar orientações individuais.</p><button onClick={()=>navigate('/enem/simulado')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white">Fazer primeiro simulado <ArrowRight className="h-4 w-4"/></button></section>:<>
<section><p className="mb-3 text-xs font-black uppercase tracking-wider text-indigo-600">O que seu comportamento está mostrando</p><div className="space-y-3">{insights.map((item,i)=><article key={item.id} className={`rounded-3xl p-5 ${tone[item.tone]}`}><div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-2xl bg-white/70 text-sm font-black">{i+1}</span><div><h2 className="text-base font-black">{item.title}</h2><p className="mt-1 text-sm leading-5 opacity-70">{item.detail}</p><div className="mt-3 rounded-2xl bg-white/65 p-3"><p className="text-[10px] font-black uppercase tracking-wider opacity-60">Treino recomendado</p><p className="mt-1 text-xs font-bold leading-5">{item.action}</p></div></div></div></article>)}</div></section>
<section className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Protocolo da próxima sessão</p><div className="mt-4 space-y-3"><div className="flex gap-3"><Clock3 className="h-4 w-4 shrink-0 text-amber-600"/><p className="text-sm"><b>Tempo:</b> se não houver caminho claro, não transforme uma questão em um buraco negro.</p></div><div className="flex gap-3"><Flag className="h-4 w-4 shrink-0 text-rose-600"/><p className="text-sm"><b>Marcação:</b> marque por uma razão específica, não por ansiedade.</p></div><div className="flex gap-3"><RefreshCw className="h-4 w-4 shrink-0 text-indigo-600"/><p className="text-sm"><b>Revisão:</b> mude resposta quando encontrar nova evidência.</p></div></div><button onClick={()=>navigate('/enem/simulado')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white">Treinar minha estratégia <ArrowRight className="h-4 w-4"/></button></section></>}
<section className="rounded-3xl bg-violet-50 p-5"><div className="flex items-center gap-2 text-violet-700"><Sparkles className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Pensamento crítico</span></div><p className="mt-2 text-sm leading-6 text-violet-950/70">O Coach não manda você seguir uma fórmula. Ele mostra padrões para que você entenda suas próprias decisões, teste estratégias e descubra o que funciona melhor para você.</p></section></main>}
