import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, BrainCircuit, CheckCircle2, FileText, Sparkles, Target } from 'lucide-react'
import { useEnemStore, type EnemArea } from '@/stores/enem'
import { useWritingStore } from '@/stores/writing'

type Area = Exclude<EnemArea,'Redação'>
type DiagnosticQuestion = { id:string; area:Area; skill:string; text:string; options:string[]; answer:number; difficulty:1|2|3 }
type Answered = { question:DiagnosticQuestion; option:number; correct:boolean }

const bank:DiagnosticQuestion[]=[
 {id:'dl1',area:'Linguagens',skill:'Inferência',text:'Em um texto, uma informação implícita é aquela que:',options:['aparece literalmente','precisa ser deduzida por pistas','está sempre no título','não tem relação com o contexto'],answer:1,difficulty:1},
 {id:'dl2',area:'Linguagens',skill:'Efeito de sentido',text:'Quando um autor usa ironia, o leitor precisa principalmente:',options:['ignorar o contexto','perceber diferença entre o dito e o sentido pretendido','buscar uma definição no dicionário','contar figuras de linguagem'],answer:1,difficulty:2},
 {id:'dl3',area:'Linguagens',skill:'Leitura crítica',text:'Dois textos defendem posições diferentes sobre o mesmo tema. Uma leitura crítica deve:',options:['escolher o mais curto','comparar argumentos e evidências','ignorar autoria','procurar palavras iguais'],answer:1,difficulty:3},
 {id:'dh1',area:'Humanas',skill:'Fonte histórica',text:'Para interpretar uma fonte histórica, é mais importante considerar:',options:['apenas a data','autoria, contexto e finalidade','somente se é antiga','se concorda com o presente'],answer:1,difficulty:1},
 {id:'dh2',area:'Humanas',skill:'Cidadania',text:'Uma política pública pode ser entendida como:',options:['ação privada sem impacto coletivo','decisão e ação voltada a problemas públicos','opinião individual','regra informal sem participação estatal'],answer:1,difficulty:2},
 {id:'dh3',area:'Humanas',skill:'Relações sociais',text:'Ao comparar desigualdades entre grupos, uma análise consistente deve considerar:',options:['um caso isolado','processos históricos e indicadores sociais','apenas opiniões pessoais','somente diferenças individuais'],answer:1,difficulty:3},
 {id:'dn1',area:'Natureza',skill:'Energia',text:'Em uma transformação de energia, é correto afirmar que:',options:['energia surge do nada','energia desaparece completamente','energia pode mudar de forma','toda energia vira matéria'],answer:2,difficulty:1},
 {id:'dn2',area:'Natureza',skill:'Ecologia',text:'A redução de uma espécie-chave em um ecossistema pode:',options:['não gerar efeito','alterar diferentes relações ecológicas','afetar apenas indivíduos da mesma espécie','impedir toda fotossíntese'],answer:1,difficulty:2},
 {id:'dn3',area:'Natureza',skill:'Evidência científica',text:'Para avaliar uma hipótese científica, o melhor caminho é:',options:['aceitá-la pela autoridade de quem falou','comparar previsões com evidências observáveis','escolher a explicação mais popular','evitar novos testes'],answer:1,difficulty:3},
 {id:'dm1',area:'Matemática',skill:'Porcentagem',text:'Um valor de R$ 200 aumenta 10%. Qual é o novo valor?',options:['R$ 210','R$ 215','R$ 220','R$ 240'],answer:2,difficulty:1},
 {id:'dm2',area:'Matemática',skill:'Proporção',text:'Se 3 cadernos custam R$ 24 no mesmo preço unitário, 5 cadernos custam:',options:['R$ 32','R$ 36','R$ 40','R$ 45'],answer:2,difficulty:2},
 {id:'dm3',area:'Matemática',skill:'Modelagem',text:'Uma corrida cobra R$ 6 fixos mais R$ 2 por quilômetro. Para 8 km, o total é:',options:['R$ 16','R$ 20','R$ 22','R$ 28'],answer:2,difficulty:3},
]
const areas:Area[]=['Linguagens','Humanas','Natureza','Matemática']
const first=(area:Area)=>bank.find(q=>q.area===area&&q.difficulty===1)!
const nextFor=(area:Area,difficulty:number,used:Set<string>)=>bank.find(q=>q.area===area&&q.difficulty===difficulty&&!used.has(q.id)) || bank.find(q=>q.area===area&&!used.has(q.id))

export function EnemDiagnosticPage(){
 const navigate=useNavigate(); const {profile,saveDiagnostic,recordAttempt}=useEnemStore(); const {createProject,saveVersion,setFocus}=useWritingStore()
 const [queue,setQueue]=useState<DiagnosticQuestion[]>(areas.map(first)); const [answered,setAnswered]=useState<Answered[]>([]); const [writing,setWriting]=useState(''); const [phase,setPhase]=useState<'questions'|'writing'|'result'>('questions')
 const current=queue[0]
 const areaScores=useMemo(()=>{const base:Record<EnemArea,number>={Linguagens:50,Humanas:50,Natureza:50,Matemática:50,Redação:50};areas.forEach(area=>{const items=answered.filter(a=>a.question.area===area);if(items.length){const weighted=items.reduce((sum,a)=>sum+(a.correct?(55+a.question.difficulty*15):20+a.question.difficulty*5),0)/items.length;base[area]=Math.round(weighted)}});const words=writing.trim().split(/\s+/).filter(Boolean).length;const position=/acredito|considero|defendo|aproxima|afasta|pode/i.test(writing);const reason=/porque|pois|visto que|uma vez que/i.test(writing);const connection=/portanto|assim|logo|desse modo|além disso/i.test(writing);base.Redação=Math.max(30,Math.min(90,30+Math.min(25,words)+(position?10:0)+(reason?15:0)+(connection?10:0)));return base},[answered,writing])
 const accuracy=answered.length?Math.round(answered.filter(a=>a.correct).length/answered.length*100):0
 const answer=(option:number)=>{if(!current)return;const correct=option===current.answer;recordAttempt({questionId:current.id,area:current.area,skill:current.skill,correct,difficulty:current.difficulty});const done=[...answered,{question:current,option,correct}];setAnswered(done);const remaining=queue.slice(1);const used=new Set(done.map(a=>a.question.id));const areaDone=done.filter(a=>a.question.area===current.area);let extra:DiagnosticQuestion|undefined;if(areaDone.length===1)extra=nextFor(current.area,correct?3:2,used);else if(areaDone.length===2&&areaDone[0].correct!==areaDone[1].correct)extra=nextFor(current.area,2,used);const nextQueue=extra?[...remaining,extra]:remaining;setQueue(nextQueue);if(!nextQueue.length)setPhase('writing')}
 const finish=()=>{const sample=writing.trim();saveDiagnostic({questionCount:answered.length,accuracy,areaScores,writingSample:sample,writingSignal:areaScores.Redação});if(sample){const id=createProject('Diagnóstico inicial — tecnologia e relações humanas','ENEM');saveVersion(id,sample);const focus=areaScores.Redação<55?'argumentacao':sample.split(/\s+/).length<55?'clareza':'tese';setFocus(id,focus)}setPhase('result')}
 const weakest=(Object.entries(areaScores) as [EnemArea,number][]).sort((a,b)=>a[1]-b[1])[0]
 const progress=Math.min(85,Math.round(answered.length/Math.max(8,answered.length+queue.length)*80))
 return <main className="ms-screen space-y-4 py-4">
  <section className="rounded-[32px] bg-gradient-to-br from-cyan-600 via-indigo-700 to-violet-700 p-5 text-white shadow-xl shadow-indigo-100"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-100">Diagnóstico adaptativo</p><h1 className="mt-2 text-2xl font-black">Perguntamos menos. Aprendemos mais.</h1></div><BrainCircuit className="h-8 w-8"/></div><p className="mt-3 text-sm leading-6 text-white/80">A próxima questão muda conforme sua resposta. Depois, uma microescrita cria o primeiro sinal do seu DNA de Escrita.</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-white transition-all" style={{width:`${phase==='questions'?progress:phase==='writing'?92:100}%`}}/></div></section>
  {phase==='questions'&&current&&<section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-black text-indigo-700">{current.area} · nível {current.difficulty}</span><span className="text-xs font-bold text-slate-400">{answered.length+1} respondidas</span></div><h2 className="mt-4 text-lg font-black leading-7">{current.text}</h2><div className="mt-4 space-y-2">{current.options.map((option,i)=><button key={option} onClick={()=>answer(i)} className="flex w-full items-center gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 text-left text-sm font-bold text-slate-800 active:scale-[.99]"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-white text-xs font-black">{String.fromCharCode(65+i)}</span><span>{option}</span></button>)}</div><p className="mt-4 text-center text-[11px] font-bold text-slate-400">A dificuldade seguinte é escolhida pelo seu sinal anterior.</p></section>}
  {phase==='writing'&&<section className="space-y-3"><div className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-fuchsia-700"><FileText className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Primeiro sinal de escrita</span></div><h2 className="mt-2 text-lg font-black">Em 3–5 frases, responda:</h2><p className="mt-2 text-sm leading-6 text-slate-600">“A tecnologia aproxima ou afasta as pessoas?” Defenda uma posição e explique pelo menos um motivo.</p><textarea value={writing} onChange={(e)=>setWriting(e.target.value)} rows={7} placeholder="Escreva com suas palavras..." className="mt-4 w-full resize-none rounded-2xl bg-slate-50 p-4 text-sm leading-6 outline-none ring-indigo-200 focus:ring-2"/><p className="mt-2 text-xs text-slate-400">Esse texto será salvo como o primeiro registro do seu portfólio de escrita e poderá orientar o Coach.</p></div><button disabled={writing.trim().length<30} onClick={finish} className="w-full rounded-2xl bg-fuchsia-600 py-4 text-sm font-black text-white disabled:opacity-40">Gerar meu primeiro mapa</button></section>}
  {phase==='result'&&<section className="space-y-4"><div className="rounded-3xl bg-emerald-50 p-5"><div className="flex items-center gap-2 text-emerald-700"><CheckCircle2 className="h-5 w-5"/><span className="text-xs font-black uppercase tracking-wider">Baseline criado</span></div><h2 className="mt-2 text-2xl font-black text-emerald-950">Seu mapa já começou a aprender você.</h2><p className="mt-2 text-sm leading-6 text-emerald-900/70">Foram {answered.length} questões escolhidas pelo caminho das suas respostas. A microescrita também entrou no seu portfólio.</p></div><div className="grid grid-cols-2 gap-3">{(Object.entries(areaScores) as [EnemArea,number][]).map(([area,score])=><div key={area} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-xs font-bold text-slate-400">{area}</p><p className="mt-1 text-2xl font-black">{score}</p><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${score}%`}}/></div></div>)}</div><div className="rounded-3xl bg-amber-50 p-5"><div className="flex items-center gap-2 text-amber-700"><Target className="h-4 w-4"/><span className="text-xs font-black uppercase tracking-wider">Primeiro foco</span></div><h3 className="mt-2 text-xl font-black text-amber-950">{weakest[0]}</h3><p className="mt-1 text-sm text-amber-900/70">É uma hipótese de trabalho, não um rótulo. Novas evidências podem mudar essa prioridade.</p></div><button onClick={()=>navigate('/enem/hoje')} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white">Ir para meu primeiro dia <ArrowRight className="h-4 w-4"/></button>{profile?.targetCourse&&<p className="text-center text-xs text-slate-400">Plano orientado para {profile.targetCourse} · meta {profile.targetScore}</p>}</section>}
  <section className="rounded-3xl bg-slate-950 p-4 text-white"><div className="flex gap-3"><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-violet-300"/><p className="text-xs leading-5 text-slate-400">O diagnóstico personaliza o estudo; não estima nota oficial do ENEM. O caminho adaptativo reduz perguntas quando o sinal é claro e investiga mais quando há dúvida.</p></div></section>
 </main>
}
