import { useEffect,useMemo,useState } from 'react'
import { CheckCircle2,History,RotateCcw,ShieldCheck,UserCheck,XCircle } from 'lucide-react'
import { platformResponsibleApi,type HumanOverride } from '@/lib/responsiblePlatformApi'

export function HumanReviewCenterPage(){
 const[rows,setRows]=useState<HumanOverride[]>([]);const[error,setError]=useState('');const[loading,setLoading]=useState(true)
 useEffect(()=>{platformResponsibleApi.overrides(150).then(r=>setRows(r.overrides)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 const stats=useMemo(()=>({accepted:rows.filter(r=>r.decision==='accepted').length,adjusted:rows.filter(r=>r.decision==='adjusted').length,rejected:rows.filter(r=>r.decision==='rejected').length}),[rows])
 return <main className="mx-auto w-full max-w-7xl space-y-6 px-4 py-8"><section className="rounded-[32px] bg-gradient-to-br from-indigo-950 via-slate-950 to-cyan-950 p-7 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Human Review Layer</p><h1 className="mt-2 text-3xl font-black">A IA recomenda. Pessoas podem revisar.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Histórico de aceitações, ajustes e rejeições humanas. Esta trilha existe para tornar decisões automatizadas contestáveis, reversíveis e auditáveis.</p></div><UserCheck className="h-9 w-9 text-cyan-300"/></div></section>
 {error&&<div className="rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
 <section className="grid gap-4 sm:grid-cols-3"><Metric label="Aceitas" value={stats.accepted} icon={<CheckCircle2 className="h-5 w-5"/>}/><Metric label="Ajustadas" value={stats.adjusted} icon={<RotateCcw className="h-5 w-5"/>}/><Metric label="Rejeitadas" value={stats.rejected} icon={<XCircle className="h-5 w-5"/>}/></section>
 <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><History className="h-5 w-5 text-indigo-600"/><div><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Trilha de auditoria</p><h2 className="text-xl font-black text-slate-950">Revisões humanas registradas</h2></div></div>{loading?<p className="mt-5 text-sm text-slate-500">Carregando revisões...</p>:rows.length===0?<div className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Nenhuma revisão humana registrada ainda.</div>:<div className="mt-5 space-y-3">{rows.map(row=><article key={row.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{row.system_key}</p><h3 className="mt-1 font-black text-slate-900">{label(row.decision)}</h3>{row.reason&&<p className="mt-2 max-w-3xl text-sm leading-5 text-slate-500">{row.reason}</p>}</div><div className="text-right"><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${tone(row.decision)}`}>{row.decision}</span><p className="mt-2 text-xs text-slate-400">{new Date(row.created_at).toLocaleString('pt-BR')}</p></div></div>{row.recommendation_id&&<p className="mt-3 text-xs font-bold text-slate-400">Recomendação: {row.recommendation_id}</p>}<div className="mt-3 flex items-center gap-2 text-xs font-bold text-slate-400"><ShieldCheck className="h-4 w-4"/>Ação humana persistida</div></article>)}</div>}</section></main>
}
function Metric({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-700">{icon}</div><p className="mt-3 text-sm text-slate-500">{label}</p><p className="text-3xl font-black text-slate-950">{value}</p></div>}
function label(decision:HumanOverride['decision']){return decision==='accepted'?'Recomendação aceita':decision==='adjusted'?'Recomendação ajustada':'Recomendação rejeitada'}
function tone(decision:HumanOverride['decision']){return decision==='accepted'?'bg-emerald-50 text-emerald-700':decision==='adjusted'?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700'}
