import { useEffect, useState } from 'react'
import { Building2, CheckCircle2, GraduationCap, Link2, Loader2, School, ShieldCheck, Unlink } from 'lucide-react'
import { institutionApi, type InstitutionLink } from '@/lib/api'

const typeLabel:Record<string,string>={school:'Escola',class:'Turma',program:'Programa',network:'Rede',course:'Curso'}

export function LearningConnectionsPage(){
 const [links,setLinks]=useState<InstitutionLink[]>([])
 const [code,setCode]=useState('')
 const [loading,setLoading]=useState(true)
 const [joining,setJoining]=useState(false)
 const [error,setError]=useState('')
 const [success,setSuccess]=useState('')
 useEffect(()=>{institutionApi.list().then(r=>setLinks(r.links)).catch(e=>setError(e instanceof Error?e.message:'Não foi possível carregar seus vínculos')).finally(()=>setLoading(false))},[])
 const join=async()=>{const normalized=code.trim().toUpperCase();if(normalized.length<4){setError('Digite o código enviado pela instituição.');return}setJoining(true);setError('');setSuccess('');try{const {link}=await institutionApi.join(normalized);setLinks(current=>[link,...current.filter(item=>item.id!==link.id)]);setCode('');setSuccess(`Conta conectada a ${link.institution.name}. Seu histórico pessoal foi preservado.`)}catch(e){setError(e instanceof Error?e.message:'Não foi possível usar este convite')}finally{setJoining(false)}}
 const leave=async(link:InstitutionLink)=>{try{await institutionApi.leave(link.id);setLinks(current=>current.filter(item=>item.id!==link.id));setSuccess('Vínculo removido. Seu histórico individual continua na sua conta.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover o vínculo')}}
 return <main className="ms-screen space-y-4 py-4">
  <section className="relative overflow-hidden rounded-[32px] bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-800 p-5 text-white"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-violet-400/15 blur-2xl"/><div className="relative"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-200">Meus vínculos</p><h1 className="mt-2 text-2xl font-black">Sua aprendizagem continua sendo sua.</h1></div><Link2 className="h-8 w-8 text-violet-200"/></div><p className="mt-3 text-sm leading-6 text-white/75">Use o MindSteps de forma independente e conecte a mesma conta a uma escola, turma, rede, curso ou programa quando receber um convite.</p></div></section>
  <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-700"><GraduationCap className="h-5 w-5"/></span><div><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Tenho um código</p><h2 className="text-lg font-black">Conectar minha conta</h2></div></div><div className="mt-4 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} onKeyDown={e=>e.key==='Enter'&&join()} placeholder="Ex.: ESCOLA2026" autoCapitalize="characters" className="min-w-0 flex-1 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-black uppercase tracking-wider outline-none focus:border-indigo-400"/><button onClick={join} disabled={joining} className="rounded-2xl bg-indigo-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{joining?<Loader2 className="h-4 w-4 animate-spin"/>:'Conectar'}</button></div><p className="mt-3 text-xs leading-5 text-slate-500">O vínculo adiciona contexto institucional à conta existente; não cria um novo histórico.</p></section>
  {error&&<section className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-800">{error}</section>}{success&&<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{success}</section>}
  <section><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Conexões ativas</p><h2 className="text-xl font-black">Onde sua conta está conectada</h2></div><span className="text-xs font-black text-indigo-700">{links.length}</span></div>{loading?<div className="flex min-h-28 items-center justify-center rounded-3xl bg-white"><Loader2 className="h-6 w-6 animate-spin text-indigo-600"/></div>:links.length===0?<div className="rounded-3xl border border-dashed border-slate-200 bg-white p-6 text-center"><School className="mx-auto h-7 w-7 text-slate-300"/><h3 className="mt-3 font-black">Modo independente ativo.</h3><p className="mt-2 text-sm leading-6 text-slate-500">Quando receber um convite institucional, conecte esta mesma conta.</p></div>:<div className="space-y-3">{links.map(link=><article key={link.id} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><Building2 className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="font-black">{link.institution.name}</h3><p className="mt-0.5 text-xs text-slate-500">{typeLabel[link.institution.type]||'Instituição'}{link.institution.city?` · ${link.institution.city}`:''}{link.institution.state?`/${link.institution.state}`:''}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black uppercase text-emerald-700">{link.status==='active'?'ativo':link.status}</span></div><div className="mt-3 flex items-center justify-between"><p className="text-[11px] font-bold text-slate-400">Papel: estudante</p><button onClick={()=>leave(link)} className="inline-flex items-center gap-1 text-xs font-black text-rose-600"><Unlink className="h-3 w-3"/>Remover</button></div></div></div></article>)}</div>}</section>
  <section className="rounded-3xl bg-emerald-50 p-5"><div className="flex items-center gap-2 text-emerald-700"><ShieldCheck className="h-5 w-5"/><span className="text-xs font-black uppercase tracking-wider">Identidade portátil</span></div><div className="mt-3 space-y-2 text-sm leading-6 text-emerald-950/75"><p className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0"/>Seu histórico individual permanece na sua conta.</p><p className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0"/>Vínculos podem adicionar contexto de turma, escola, curso ou programa.</p><p className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0"/>Remover um vínculo não apaga sua trajetória pessoal.</p></div></section>
 </main>
}
