import { Link } from 'react-router-dom'
import { BrainCircuit, Database, GraduationCap, ShieldCheck, Sparkles, UserCheck, Users } from 'lucide-react'

const cards=[
 {to:'/transparencia-ia',title:'Por que o MindSteps decidiu isso?',detail:'Decisões, evidências, confiança e necessidade de revisão humana.',icon:BrainCircuit,tone:'violet'},
 {to:'/direitos-dados',title:'Direitos & Dados',detail:'Controle personalização, compartilhamento institucional, pesquisa e retenção.',icon:Database,tone:'indigo'},
 {to:'/ia-cidadania',title:'IA & Cidadania',detail:'Aprender com IA e sobre IA, com missões adequadas à etapa escolar.',icon:Sparkles,tone:'cyan'},
 {to:'/revisoes-humanas',title:'Revisões humanas',detail:'Veja quando recomendações foram aceitas, ajustadas ou rejeitadas por pessoas.',icon:UserCheck,tone:'emerald'},
 {to:'/professor/ia',title:'Teacher Copilot',detail:'Sinais pedagógicos com evidência, ação sugerida e decisão final do professor.',icon:GraduationCap,tone:'amber'},
 {to:'/escola/governanca-ia',title:'Governança de IA',detail:'Política institucional, regras por idade, dados, incidentes e prontidão.',icon:ShieldCheck,tone:'rose'},
] as const

const styles:Record<string,string>={violet:'bg-violet-50 text-violet-700',indigo:'bg-indigo-50 text-indigo-700',cyan:'bg-cyan-50 text-cyan-700',emerald:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',rose:'bg-rose-50 text-rose-700'}

export function ResponsibleLearningHomePage(){return <main className="mx-auto w-full max-w-7xl space-y-7 px-4 py-8"><section className="overflow-hidden rounded-[34px] bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-900 p-8 text-white"><div className="max-w-4xl"><div className="flex items-center gap-2 text-violet-200"><ShieldCheck className="h-5 w-5"/><p className="text-xs font-black uppercase tracking-[.2em]">Responsible Learning OS</p></div><h1 className="mt-4 text-4xl font-black leading-tight">Um centro para entender, controlar e governar a IA educacional.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/75">O MindSteps separa aprendizagem, direitos, explicabilidade, revisão humana, formação docente e governança institucional. A IA pode recomendar; pessoas continuam no comando.</p><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">Humano no centro</span><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">Decisões explicáveis</span><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">Direitos configuráveis</span><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">Aprender com e sobre IA</span></div></div></section><section><div className="mb-4 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Centro de confiança</p><h2 className="mt-1 text-2xl font-black text-slate-950">Escolha o que você quer entender ou controlar.</h2></div><div className="hidden items-center gap-2 text-xs font-bold text-slate-400 md:flex"><Users className="h-4 w-4"/>Aluno · Professor · Família · Escola</div></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{cards.map(({to,title,detail,icon:Icon,tone})=><Link key={to} to={to} className="group rounded-3xl bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className={`flex h-11 w-11 items-center justify-center rounded-2xl ${styles[tone]}`}><Icon className="h-5 w-5"/></div><h3 className="mt-4 text-lg font-black text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{detail}</p><p className="mt-4 text-xs font-black text-slate-950">Abrir centro →</p></Link>)}</div></section><section className="rounded-3xl bg-emerald-50 p-6"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Princípio operacional</p><h2 className="mt-2 text-xl font-black text-emerald-950">IA recomendando não significa IA decidindo sozinha.</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-emerald-950/70">Quando impacto, risco ou incerteza aumentam, o Learning OS pode exigir revisão humana, registrar a justificativa e permitir contestação. Esse desenho é parte do produto, não apenas uma política publicada.</p></section></main>}
