import { useEffect,useMemo,useState } from 'react'
import { AlertTriangle,Building2,CheckCircle2,Save,ShieldCheck,Siren } from 'lucide-react'
import { toast } from 'sonner'
import { platformResponsibleApi,type ManagedInstitution } from '@/lib/responsiblePlatformApi'

export function SchoolAIGovernancePage(){
 const[institutions,setInstitutions]=useState<ManagedInstitution[]>([]);const[selected,setSelected]=useState('');const[policy,setPolicy]=useState<Record<string,unknown>>({});const[readiness,setReadiness]=useState<Record<string,unknown>>({});const[incidents,setIncidents]=useState<Array<Record<string,unknown>>>([]);const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[incidentCategory,setIncidentCategory]=useState('conteudo_incorreto');const[incidentSeverity,setIncidentSeverity]=useState<'low'|'medium'|'high'|'critical'>('low');const[incidentDescription,setIncidentDescription]=useState('')
 const load=async(id:string)=>{if(!id)return;try{const[p,r,i]=await Promise.all([platformResponsibleApi.schoolPolicy(id),platformResponsibleApi.readiness(id),platformResponsibleApi.incidents(id)]);setPolicy(p.policy||{});setReadiness(r);setIncidents(i.incidents)}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar governança')}}
 useEffect(()=>{platformResponsibleApi.institutions().then(r=>{setInstitutions(r.institutions);if(r.institutions[0])setSelected(r.institutions[0].id)}).catch(e=>setError(e.message))},[])
 useEffect(()=>{void load(selected)},[selected])
 const score=Number(readiness.score||0);const allowed=useMemo(()=>Array.isArray(policy.allowed_systems)?policy.allowed_systems as string[]:[],[policy]);const prohibited=useMemo(()=>Array.isArray(policy.prohibited_uses)?policy.prohibited_uses as string[]:[],[policy]);const ageRules=(policy.age_rules||{}) as Record<string,unknown>;const dataRules=(policy.data_rules||{}) as Record<string,unknown>;const humanRules=(policy.human_review_rules||{}) as Record<string,unknown>
 const save=async()=>{if(!selected)return;setSaving(true);try{const body={title:String(policy.title||'Política de IA da instituição'),status:String(policy.status||'draft'),allowedSystems:allowed,prohibitedUses:prohibited,ageRules,dataRules,humanReviewRules:humanRules,incidentContact:policy.incident_contact?String(policy.incident_contact):null};const r=await platformResponsibleApi.saveSchoolPolicy(selected,body);setPolicy(r.policy);setReadiness(await platformResponsibleApi.readiness(selected));toast.success('Política de IA salva')}catch(e){setError(e instanceof Error?e.message:'Erro ao salvar')}finally{setSaving(false)}}
 const report=async()=>{if(!selected||incidentDescription.trim().length<5){toast.error('Descreva o incidente com mais detalhes');return}setSaving(true);try{await platformResponsibleApi.registerIncident(selected,{severity:incidentSeverity,category:incidentCategory,description:incidentDescription.trim()});setIncidentDescription('');await load(selected);toast.success('Incidente registrado para acompanhamento')}catch(e){toast.error(e instanceof Error?e.message:'Erro ao registrar incidente')}finally{setSaving(false)}}
 return <main className="mx-auto w-full max-w-7xl space-y-6 px-4 py-8"><section className="rounded-[32px] bg-slate-950 p-7 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">School AI Governance</p><h1 className="mt-2 text-3xl font-black">Governar IA é parte da gestão pedagógica.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Defina sistemas autorizados, limites por idade, regras de dados, revisão humana e resposta a incidentes. O centro torna a política institucional operável.</p></div><ShieldCheck className="h-9 w-9 text-cyan-300"/></div></section>{error&&<div className="rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
 <section className="flex flex-wrap items-center gap-3 rounded-3xl bg-white p-5 shadow-sm"><Building2 className="h-5 w-5 text-slate-500"/><select value={selected} onChange={e=>setSelected(e.target.value)} className="min-w-64 rounded-xl bg-slate-50 px-3 py-2 text-sm font-bold outline-none">{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><div className="ml-auto rounded-2xl bg-cyan-50 px-4 py-2"><span className="text-xs font-bold text-cyan-700">Prontidão</span><span className="ml-2 text-xl font-black text-cyan-950">{score}%</span></div></section>
 <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="space-y-4"><div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Política institucional</p><input value={String(policy.title||'Política de IA da instituição')} onChange={e=>setPolicy(p=>({...p,title:e.target.value}))} className="mt-3 w-full rounded-2xl bg-slate-50 p-3 text-sm font-bold outline-none"/><div className="mt-4 grid gap-4 md:grid-cols-2"><TextList title="Sistemas autorizados" values={allowed} onChange={values=>setPolicy(p=>({...p,allowed_systems:values}))} placeholder="socratic_tutor\nwriting_coach"/><TextList title="Usos proibidos" values={prohibited} onChange={values=>setPolicy(p=>({...p,prohibited_uses:values}))} placeholder="decisão automática de alto impacto\npublicidade comportamental"/></div>
 <div className="mt-5 grid gap-4 md:grid-cols-3"><RuleBox title="Regras por idade" checks={[['early_requires_mediation','Anos iniciais com mediação'],['teen_source_checks','Adolescentes verificam fontes'],['offline_balance','Equilíbrio fora da tela']]} values={ageRules} onChange={v=>setPolicy(p=>({...p,age_rules:v}))}/><RuleBox title="Regras de dados" checks={[['minimum_data','Minimização de dados'],['no_ads','Sem publicidade comportamental'],['retention_review','Revisar retenção']]} values={dataRules} onChange={v=>setPolicy(p=>({...p,data_rules:v}))}/><RuleBox title="Revisão humana" checks={[['high_impact_required','Alto impacto exige humano'],['low_confidence_required','Baixa confiança exige revisão'],['student_contestation','Aluno pode contestar']]} values={humanRules} onChange={v=>setPolicy(p=>({...p,human_review_rules:v}))}/></div>
 <label className="mt-4 block text-xs font-black uppercase tracking-wider text-slate-400">Contato para incidentes</label><input value={String(policy.incident_contact||'')} onChange={e=>setPolicy(p=>({...p,incident_contact:e.target.value}))} placeholder="responsavel@escola.br" className="mt-2 w-full rounded-2xl bg-slate-50 p-3 text-sm outline-none"/><button onClick={save} disabled={saving||!selected} className="mt-4 flex items-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Salvando...':'Salvar política'}</button></div>
 <div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Checklist de prontidão</p><div className="mt-4 grid gap-2 md:grid-cols-2">{Object.entries((readiness.checks||{}) as Record<string,boolean>).map(([k,v])=><div key={k} className="flex items-center gap-2 rounded-2xl bg-slate-50 p-3 text-sm font-bold text-slate-700">{v?<CheckCircle2 className="h-4 w-4 text-emerald-500"/>:<AlertTriangle className="h-4 w-4 text-amber-500"/>}{k}</div>)}</div></div></section>
 <aside className="space-y-4"><div className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-rose-600"><Siren className="h-5 w-5"/><p className="text-xs font-black uppercase tracking-wider">Registrar incidente</p></div><div className="mt-4 grid grid-cols-2 gap-2"><select value={incidentCategory} onChange={e=>setIncidentCategory(e.target.value)} className="rounded-xl bg-slate-50 px-3 py-2 text-sm font-bold"><option value="conteudo_incorreto">Conteúdo incorreto</option><option value="privacidade">Privacidade</option><option value="vies">Possível viés</option><option value="bem_estar">Bem-estar</option><option value="uso_indevido">Uso indevido</option></select><select value={incidentSeverity} onChange={e=>setIncidentSeverity(e.target.value as typeof incidentSeverity)} className="rounded-xl bg-slate-50 px-3 py-2 text-sm font-bold"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div><textarea value={incidentDescription} onChange={e=>setIncidentDescription(e.target.value)} rows={4} placeholder="Descreva o que aconteceu, contexto e impacto observado." className="mt-2 w-full rounded-2xl bg-slate-50 p-3 text-sm outline-none"/><button onClick={report} disabled={saving} className="mt-3 w-full rounded-xl bg-rose-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">Registrar para revisão</button></div>
 <div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-rose-600">Incidentes e revisão</p><h2 className="mt-1 text-xl font-black">Acompanhamento operacional</h2><p className="mt-2 text-sm text-slate-500">Incidentes abertos: <b>{String(readiness.openIncidents||0)}</b></p><div className="mt-4 space-y-3">{incidents.length===0?<div className="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">Nenhum incidente registrado.</div>:incidents.slice(0,10).map((i,index)=><article key={String(i.id||index)} className="rounded-2xl bg-rose-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-rose-600">{String(i.severity||'low')} · {String(i.category||'incidente')}</p><p className="mt-2 text-sm font-bold leading-5 text-rose-950">{String(i.description||'')}</p></article>)}</div></div></aside></div></main>}
function TextList({title,values,onChange,placeholder}:{title:string;values:string[];onChange:(v:string[])=>void;placeholder:string}){return <div><label className="text-xs font-black uppercase tracking-wider text-slate-400">{title}</label><textarea value={values.join('\n')} onChange={e=>onChange(e.target.value.split('\n').map(v=>v.trim()).filter(Boolean))} rows={5} placeholder={placeholder} className="mt-2 w-full rounded-2xl bg-slate-50 p-3 text-sm outline-none"/></div>}
function RuleBox({title,checks,values,onChange}:{title:string;checks:Array<[string,string]>;values:Record<string,unknown>;onChange:(v:Record<string,unknown>)=>void}){return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{title}</p><div className="mt-3 space-y-2">{checks.map(([key,label])=><label key={key} className="flex items-center gap-2 text-xs font-bold text-slate-700"><input type="checkbox" checked={values[key]===true} onChange={e=>onChange({...values,[key]:e.target.checked})}/>{label}</label>)}</div></div>}
