import { Router } from 'express'
import { z } from 'zod'
import { authMiddleware } from './auth.js'
import { getProfileByUserId } from '../db/index.js'
import { buildLearningOSPlan, listLearningOSRuns, persistLearningOSRun } from '../services/learningOperatingSystem.js'
import { getOutcomeSummary, recordOutcome } from '../services/learningOSGovernance.js'
import { getInstitutionLearningPolicy, saveInstitutionLearningPolicy } from '../services/institutionLearningPolicy.js'
import { listTransferChecks, saveTransferCheck, summarizeIndependence } from '../services/independentLearning.js'
import { evaluateIndependentAnswer, generateIndependentChallenge } from '../services/independentAssessment.js'

const router=Router();router.use(authMiddleware)
const schema=z.object({actor:z.enum(['student','teacher','guardian','institution']).optional(),intent:z.enum(['learn','practice','verify','create','review','plan','reflect']).optional(),message:z.string().max(8000).optional(),subject:z.string().max(120).optional(),skill:z.string().max(160).optional(),sessionMinutes:z.number().min(0).max(600).optional(),interactionCount:z.number().int().min(0).max(1000).optional(),frustration:z.boolean().optional(),evidence:z.record(z.unknown()).optional(),requestedSystemKey:z.string().max(120).optional(),forceHumanReview:z.boolean().optional(),institutionId:z.string().uuid().nullable().optional(),highImpact:z.boolean().optional(),incidentSignal:z.boolean().optional()})
router.post('/plan',async(req,res)=>{try{const body=schema.parse(req.body||{});const profile=await getProfileByUserId(req.userId);if(!profile)return res.status(404).json({message:'Perfil não encontrado'});const input={userId:req.userId,profile,...body};res.json({plan:await buildLearningOSPlan(input)})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.errors[0].message});res.status(500).json({message:e instanceof Error?e.message:'Não foi possível gerar o plano'})}})
router.post('/execute',async(req,res)=>{try{const body=schema.parse(req.body||{});const profile=await getProfileByUserId(req.userId);if(!profile)return res.status(404).json({message:'Perfil não encontrado'});const input={userId:req.userId,profile,...body};const plan=await buildLearningOSPlan(input);const persisted=await persistLearningOSRun(input,plan);res.json({plan,...persisted})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.errors[0].message});res.status(500).json({message:e instanceof Error?e.message:'Não foi possível executar o Learning OS'})}})
router.get('/runs',async(req,res)=>{try{res.json({runs:await listLearningOSRuns(req.userId,Math.min(100,Number(req.query.limit)||30))})}catch(e){res.status(500).json({message:e instanceof Error?e.message:'Não foi possível carregar execuções'})}})
const outcomeSchema=z.object({runId:z.string().uuid(),before:z.number().nullable().optional(),after:z.number().nullable().optional(),completed:z.boolean().optional(),studentFeedback:z.enum(['helped','neutral','did_not_help']).nullable().optional(),teacherFeedback:z.enum(['confirmed','adjusted','rejected']).nullable().optional(),notes:z.string().max(2000).nullable().optional()})
router.post('/outcomes',async(req,res)=>{try{const body=outcomeSchema.parse(req.body||{});res.json({outcome:await recordOutcome({userId:req.userId,...body})})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.errors[0].message});res.status(500).json({message:e instanceof Error?e.message:'Não foi possível registrar o resultado'})}})
router.get('/outcomes/summary',async(req,res)=>{try{res.json({summary:await getOutcomeSummary(req.userId,req.query.systemKey?String(req.query.systemKey):undefined)})}catch(e){res.status(500).json({message:e instanceof Error?e.message:'Não foi possível resumir os resultados'})}})

const transferSchema=z.object({subject:z.string().max(120).nullable().optional(),skill:z.string().max(160).nullable().optional(),source:z.string().max(80).optional(),assistedScore:z.number().min(0).max(100).nullable().optional(),independentScore:z.number().min(0).max(100).nullable().optional(),helpLevel:z.number().int().min(0).max(4).optional(),attemptBeforeHelp:z.boolean().optional(),completed:z.boolean().optional(),metadata:z.record(z.unknown()).optional()})
router.post('/transfer-checks',async(req,res)=>{try{const body=transferSchema.parse(req.body||{});res.json({check:await saveTransferCheck({userId:req.userId,...body})})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.errors[0].message});res.status(500).json({message:e instanceof Error?e.message:'Não foi possível registrar o check independente'})}})
router.get('/transfer-checks',async(req,res)=>{try{const rows=await listTransferChecks(req.userId,Math.min(100,Number(req.query.limit)||50));res.json({checks:rows,summary:summarizeIndependence(rows)})}catch(e){res.status(500).json({message:e instanceof Error?e.message:'Não foi possível carregar autonomia'})}})
const challengeSchema=z.object({subject:z.string().min(2).max(120),skill:z.string().max(160).optional(),context:z.string().max(1500).optional()})
router.post('/transfer-challenge',async(req,res)=>{try{const body=challengeSchema.parse(req.body||{});const profile=await getProfileByUserId(req.userId);if(!profile)return res.status(404).json({message:'Perfil não encontrado'});res.json({challenge:await generateIndependentChallenge({subject:body.subject,skill:body.skill,context:body.context,ageGroup:profile.age_group})})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.errors[0].message});res.status(500).json({message:e instanceof Error?e.message:'Não foi possível criar o desafio independente'})}})
const evaluateSchema=z.object({question:z.string().min(5).max(4000),answer:z.string().min(2).max(8000),subject:z.string().min(2).max(120),skill:z.string().max(160).optional(),rubric:z.array(z.string()).max(5).optional(),assistedScore:z.number().min(0).max(100).optional(),helpLevel:z.number().int().min(0).max(4).optional(),attemptBeforeHelp:z.boolean().optional(),source:z.string().max(80).optional()})
router.post('/transfer-challenge/evaluate',async(req,res)=>{try{const body=evaluateSchema.parse(req.body||{});const evaluation=await evaluateIndependentAnswer(body);const check=await saveTransferCheck({userId:req.userId,subject:body.subject,skill:body.skill,source:body.source||'no_help_check',assistedScore:body.assistedScore,independentScore:evaluation.score,helpLevel:body.helpLevel,attemptBeforeHelp:body.attemptBeforeHelp,completed:true,metadata:{question:body.question,rubric:body.rubric||[],feedback:evaluation.feedback,evidence:evaluation.evidence,passed:evaluation.passed}});const rows=await listTransferChecks(req.userId,50);res.json({evaluation,check,summary:summarizeIndependence(rows)})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.errors[0].message});res.status(500).json({message:e instanceof Error?e.message:'Não foi possível avaliar o check independente'})}})

const policySchema=z.object({enabled:z.boolean().optional(),allowedSystems:z.array(z.string()).optional(),blockedSystems:z.array(z.string()).optional(),forceHumanReviewFor:z.array(z.string()).optional(),maxConfidenceForAutonomy:z.number().min(0).max(1).optional(),requireSourceReminder:z.boolean().optional(),requireOfflineBalance:z.boolean().optional(),notes:z.string().max(4000).nullable().optional()})
router.get('/institutions/:institutionId/policy',async(req,res)=>{try{res.json({policy:await getInstitutionLearningPolicy(req.userId,req.params.institutionId)})}catch(e){res.status(403).json({message:e instanceof Error?e.message:'Não foi possível carregar a política'})}})
router.put('/institutions/:institutionId/policy',async(req,res)=>{try{const body=policySchema.parse(req.body||{});res.json({policy:await saveInstitutionLearningPolicy(req.userId,req.params.institutionId,body)})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.errors[0].message});res.status(403).json({message:e instanceof Error?e.message:'Não foi possível salvar a política'})}})
export default router
