import { supabase, type StudentProfile } from '../db/index.js'

export type ConfidenceBand='low'|'medium'|'high'
export function confidenceBand(value:number):ConfidenceBand{return value>=.8?'high':value>=.55?'medium':'low'}

export function buildLearningDecision(input:{systemKey:string;decisionType:string;recommendationId?:string;subject?:string;skill?:string;evidence?:Record<string,unknown>;confidence?:number;explanation:string;humanReviewRequired?:boolean}){
 const confidence=Math.max(0,Math.min(1,input.confidence??.5))
 return {...input,evidence:input.evidence??{},confidence,confidenceBand:confidenceBand(confidence),humanReviewRequired:input.humanReviewRequired??confidence<.7}
}
export async function saveLearningDecision(userId:string,input:ReturnType<typeof buildLearningDecision>){const {data,error}=await supabase.from('mindsteps_learning_decisions').insert({user_id:userId,system_key:input.systemKey,decision_type:input.decisionType,recommendation_id:input.recommendationId||null,subject:input.subject||null,skill:input.skill||null,evidence:input.evidence,confidence:input.confidence,explanation:input.explanation,human_review_required:input.humanReviewRequired}).select('*').single();if(error)throw new Error(error.message);return data}
export async function listLearningDecisions(userId:string,limit=30){const {data,error}=await supabase.from('mindsteps_learning_decisions').select('*').eq('user_id',userId).order('created_at',{ascending:false}).limit(limit);if(error)throw new Error(error.message);return data||[]}

export type FairnessObservationInput={institutionId?:string|null;systemKey:string;metricKey:string;cohortKey:string;cohortValue:string;sampleSize:number;metricValue:number;baselineValue?:number|null;metadata?:Record<string,unknown>}
export function assessFairnessObservation(input:FairnessObservationInput){const disparity=input.baselineValue==null?null:Number((input.metricValue-input.baselineValue).toFixed(3));const abs=disparity==null?0:Math.abs(disparity);const severity=input.sampleSize<20?'info':abs>=.2?'review':abs>=.1?'watch':'info';return{...input,disparity,severity,notice:input.sampleSize<20?'Amostra pequena: não interpretar como evidência de desigualdade.':severity==='review'?'Diferença persistente merece revisão humana e análise contextual.':'Sinal para acompanhamento, sem rotular estudantes.'}}
export async function saveFairnessObservation(input:FairnessObservationInput){const a=assessFairnessObservation(input);const {data,error}=await supabase.from('mindsteps_ai_fairness_observations').insert({institution_id:a.institutionId||null,system_key:a.systemKey,metric_key:a.metricKey,cohort_key:a.cohortKey,cohort_value:a.cohortValue,sample_size:a.sampleSize,metric_value:a.metricValue,baseline_value:a.baselineValue??null,disparity:a.disparity,severity:a.severity,metadata:a.metadata||{}}).select('*').single();if(error)throw new Error(error.message);return{observation:data,assessment:a}}

export type ChildRightsPreferences={aiPersonalizationAllowed:boolean;institutionSharingAllowed:boolean;researchUseAllowed:boolean;productImprovementAllowed:boolean;marketingAllowed:boolean;retentionMode:'minimum'|'standard';guardianUserId?:string|null;noticeVersion?:string}
export const DEFAULT_CHILD_RIGHTS:ChildRightsPreferences={aiPersonalizationAllowed:true,institutionSharingAllowed:false,researchUseAllowed:false,productImprovementAllowed:true,marketingAllowed:false,retentionMode:'minimum',guardianUserId:null,noticeVersion:'2026-08'}
export async function getChildRightsPreferences(userId:string){const {data,error}=await supabase.from('mindsteps_child_rights_preferences').select('*').eq('user_id',userId).maybeSingle();if(error)throw new Error(error.message);return data||{user_id:userId,ai_personalization_allowed:DEFAULT_CHILD_RIGHTS.aiPersonalizationAllowed,institution_sharing_allowed:false,research_use_allowed:false,product_improvement_allowed:true,marketing_allowed:false,retention_mode:'minimum',data_processing_notice_version:'2026-08'}}
export async function saveChildRightsPreferences(userId:string,input:Partial<ChildRightsPreferences>){const current=await getChildRightsPreferences(userId);const payload={user_id:userId,guardian_user_id:input.guardianUserId??current.guardian_user_id??null,data_processing_notice_version:input.noticeVersion??current.data_processing_notice_version??'2026-08',ai_personalization_allowed:input.aiPersonalizationAllowed??current.ai_personalization_allowed??true,institution_sharing_allowed:input.institutionSharingAllowed??current.institution_sharing_allowed??false,research_use_allowed:input.researchUseAllowed??current.research_use_allowed??false,product_improvement_allowed:input.productImprovementAllowed??current.product_improvement_allowed??true,marketing_allowed:input.marketingAllowed??current.marketing_allowed??false,retention_mode:input.retentionMode??current.retention_mode??'minimum',updated_at:new Date().toISOString()};const {data,error}=await supabase.from('mindsteps_child_rights_preferences').upsert(payload,{onConflict:'user_id'}).select('*').single();if(error)throw new Error(error.message);return data}

export type UnpluggedMission={id:string;title:string;goal:string;materials:string[];steps:string[];reflection:string;learningIds:number[];minutes:number}
export function buildUnpluggedMission(profile:StudentProfile,learningId?:number):UnpluggedMission{const young=profile.age_group==='6-10';const mid=profile.age_group==='11-14';const id=learningId??(young?2:mid?5:6);const catalog:Record<number,UnpluggedMission>={2:{id:'pattern-cards',title:'Detetive de padrões',goal:'Perceber como regras classificam informações.',materials:['10 objetos ou cartões'],steps:['Separe os objetos em dois grupos usando uma regra secreta.','Peça a alguém para adivinhar a regra.','Mude um objeto de lugar e observe se a regra ainda funciona.'],reflection:'Uma regra simples consegue explicar todos os casos? Onde ela falhou?',learningIds:[1,2],minutes:12},5:{id:'data-trail',title:'Rastro de dados sem tela',goal:'Entender como dados viram recomendações.',materials:['papel','lápis'],steps:['Liste cinco escolhas que você fez hoje.','Imagine quais dados um aplicativo precisaria para prever sua próxima escolha.','Risque dados que seriam excessivos ou privados.'],reflection:'Qual é o mínimo de dados necessário para ajudar sem invadir?',learningIds:[5,10,11],minutes:15},6:{id:'bias-sort',title:'Quando a regra fica injusta',goal:'Identificar como uma classificação pode produzir vieses.',materials:['12 cartões com perfis fictícios'],steps:['Crie uma regra para escolher quem receberia uma oportunidade.','Teste a regra em todos os cartões.','Procure quem ficou prejudicado sem relação com o objetivo.'],reflection:'Que informação não deveria influenciar a decisão? Como revisar a regra?',learningIds:[6,9,10],minutes:18}};return catalog[id]||catalog[young?2:mid?5:6]}
