import { supabase } from '../db/index.js'

type GovernanceRole='owner'|'admin'|'coordinator'|'teacher'
async function membership(userId:string,institutionId:string){const {data,error}=await supabase.from('mindsteps_institution_members').select('role,status').eq('user_id',userId).eq('institution_id',institutionId).eq('status','active').single();if(error||!data)throw new Error('Você não tem acesso a esta instituição');return data as {role:GovernanceRole}}
export async function getGovernancePolicy(userId:string,institutionId:string){await membership(userId,institutionId);const {data,error}=await supabase.from('mindsteps_ai_school_policies').select('*').eq('institution_id',institutionId).maybeSingle();if(error)throw new Error(error.message);return data}
export async function saveGovernancePolicy(userId:string,institutionId:string,input:any){const m=await membership(userId,institutionId);if(!['owner','admin','coordinator'].includes(m.role))throw new Error('Seu perfil não pode alterar a política de IA');const row={institution_id:institutionId,updated_by:userId,title:input.title||'Política de IA da instituição',status:input.status||'draft',allowed_systems:input.allowedSystems||[],prohibited_uses:input.prohibitedUses||[],age_rules:input.ageRules||{},data_rules:input.dataRules||{},human_review_rules:input.humanReviewRules||{},incident_contact:input.incidentContact||null,updated_at:new Date().toISOString()};const {data,error}=await supabase.from('mindsteps_ai_school_policies').upsert(row,{onConflict:'institution_id'}).select('*').single();if(error)throw new Error(error.message);return data}
export async function registerIncident(userId:string,institutionId:string,input:any){await membership(userId,institutionId);const {data,error}=await supabase.from('mindsteps_ai_incidents').insert({institution_id:institutionId,reported_by:userId,system_key:input.systemKey||null,severity:input.severity||'low',category:input.category,description:input.description,status:'open',metadata:input.metadata||{}}).select('*').single();if(error)throw new Error(error.message);return data}
export async function listIncidents(userId:string,institutionId:string){await membership(userId,institutionId);const {data,error}=await supabase.from('mindsteps_ai_incidents').select('*').eq('institution_id',institutionId).order('created_at',{ascending:false}).limit(100);if(error)throw new Error(error.message);return data||[]}
export async function governanceReadiness(userId:string,institutionId:string){await membership(userId,institutionId);const [policy,incidents]=await Promise.all([getGovernancePolicy(userId,institutionId),listIncidents(userId,institutionId)]);const checks=[Boolean(policy),Boolean(policy?.allowed_systems?.length),Boolean(policy?.prohibited_uses?.length),Boolean(policy?.age_rules&&Object.keys(policy.age_rules).length),Boolean(policy?.data_rules&&Object.keys(policy.data_rules).length),Boolean(policy?.human_review_rules&&Object.keys(policy.human_review_rules).length),Boolean(policy?.incident_contact)];const score=Math.round(checks.filter(Boolean).length/checks.length*100);return{score,status:score>=85?'ready':score>=55?'partial':'initial',checks:{policy:Boolean(policy),allowedSystems:checks[1],prohibitedUses:checks[2],ageRules:checks[3],dataRules:checks[4],humanReview:checks[5],incidentContact:checks[6]},openIncidents:incidents.filter((i:any)=>i.status==='open').length}}
