import { supabase } from '../db/index.js'

type Role='owner'|'admin'|'coordinator'|'teacher'
async function member(userId:string,institutionId:string){const{data,error}=await supabase.from('mindsteps_institution_members').select('role,status').eq('user_id',userId).eq('institution_id',institutionId).eq('status','active').maybeSingle();if(error||!data)throw new Error('Você não tem acesso a esta instituição');return data as{role:Role,status:string}}
async function manage(userId:string,institutionId:string){const m=await member(userId,institutionId);if(!['owner','admin','coordinator'].includes(m.role))throw new Error('Seu perfil não tem permissão para esta ação');return m}
async function audit(institutionId:string,userId:string,action:string,target:string,metadata:Record<string,unknown>={}){await supabase.from('mindsteps_school_audit_log').insert({institution_id:institutionId,actor_user_id:userId,action,entity_type:'teaching_scope',entity_id:target,metadata})}

export async function assignTeacher(userId:string,institutionId:string,input:{teacherUserId:string;classId:string;subject?:string|null}){await manage(userId,institutionId);const[{data:teacher,error:teacherError},{data:schoolClass,error:classError}]=await Promise.all([supabase.from('mindsteps_institution_members').select('user_id,role,status').eq('institution_id',institutionId).eq('user_id',input.teacherUserId).eq('role','teacher').eq('status','active').maybeSingle(),supabase.from('mindsteps_school_classes').select('id,name,status').eq('institution_id',institutionId).eq('id',input.classId).eq('status','active').maybeSingle()]);if(teacherError)throw new Error(teacherError.message);if(classError)throw new Error(classError.message);if(!teacher)throw new Error('Professor ativo não encontrado nesta instituição');if(!schoolClass)throw new Error('Turma ativa não encontrada nesta instituição');const subject=input.subject?.trim()||null;let data:any,error:any;if(subject===null){const existing=await supabase.from('mindsteps_school_class_teachers').select('*').eq('institution_id',institutionId).eq('class_id',input.classId).eq('teacher_user_id',input.teacherUserId).is('subject',null).order('created_at',{ascending:true}).limit(1).maybeSingle();if(existing.error)throw new Error(existing.error.message);if(existing.data){const updated=await supabase.from('mindsteps_school_class_teachers').update({status:'active'}).eq('id',existing.data.id).eq('institution_id',institutionId).select('*').single();data=updated.data;error=updated.error}else{const inserted=await supabase.from('mindsteps_school_class_teachers').insert({institution_id:institutionId,class_id:input.classId,teacher_user_id:input.teacherUserId,subject:null,status:'active',created_by:userId}).select('*').single();data=inserted.data;error=inserted.error}}else{const saved=await supabase.from('mindsteps_school_class_teachers').upsert({institution_id:institutionId,class_id:input.classId,teacher_user_id:input.teacherUserId,subject,status:'active',created_by:userId},{onConflict:'institution_id,class_id,teacher_user_id,subject'}).select('*').single();data=saved.data;error=saved.error}if(error||!data)throw new Error(error?.message||'Não foi possível vincular o professor');await audit(institutionId,userId,'teaching_scope.assign',data.id,{teacherUserId:input.teacherUserId,classId:input.classId,subject});return data}

export async function setTeacherAssignmentStatus(userId:string,institutionId:string,assignmentId:string,status:'active'|'inactive'){await manage(userId,institutionId);const{data,error}=await supabase.from('mindsteps_school_class_teachers').update({status}).eq('institution_id',institutionId).eq('id',assignmentId).select('*').single();if(error)throw new Error(error.message);await audit(institutionId,userId,status==='active'?'teaching_scope.restore':'teaching_scope.remove',assignmentId);return data}

export async function listTeachingScope(userId:string,institutionId:string){const m=await member(userId,institutionId);let q=supabase.from('mindsteps_school_class_teachers').select('id,class_id,teacher_user_id,subject,status,created_at').eq('institution_id',institutionId).eq('status','active').order('created_at',{ascending:true});if(m.role==='teacher')q=q.eq('teacher_user_id',userId);const{data,error}=await q;if(error)throw new Error(error.message);return{assignments:data||[],count:(data||[]).length}}

export async function getTeacherRoster(userId:string,institutionId:string,classId:string){const m=await member(userId,institutionId);if(m.role==='teacher'){const{data:scope,error:scopeError}=await supabase.from('mindsteps_school_class_teachers').select('id').eq('institution_id',institutionId).eq('class_id',classId).eq('teacher_user_id',userId).eq('status','active').limit(1).maybeSingle();if(scopeError)throw new Error(scopeError.message);if(!scope)throw new Error('Você não está vinculado a esta turma')}const{data,error}=await supabase.from('mindsteps_student_links').select('id,user_id,status,joined_at,class_id,external_id').eq('institution_id',institutionId).eq('class_id',classId).eq('status','active').order('joined_at',{ascending:true});if(error)throw new Error(error.message);return{students:data||[],count:(data||[]).length}}
