import { supabase } from '../db/index.js'

type Role='owner'|'admin'|'coordinator'|'teacher'
async function access(userId:string,institutionId:string,roles?:Role[]){const{data,error}=await supabase.from('mindsteps_institution_members').select('role').eq('user_id',userId).eq('institution_id',institutionId).eq('status','active').maybeSingle();if(error||!data)throw new Error('Você não tem acesso a esta instituição');if(roles&&!roles.includes(data.role as Role))throw new Error('Seu perfil não tem permissão para esta ação')}
async function audit(institutionId:string,userId:string,action:string,entityId:string){await supabase.from('mindsteps_school_audit_log').insert({institution_id:institutionId,actor_user_id:userId,action,entity_type:'student',entity_id:entityId})}

export async function getRoster(userId:string,institutionId:string,status='active'){await access(userId,institutionId);const{data,error,count}=await supabase.from('mindsteps_student_links').select('id,user_id,status,joined_at,left_at,class_id,external_id',{count:'exact'}).eq('institution_id',institutionId).eq('status',status).order('joined_at',{ascending:false});if(error)throw new Error(error.message);return{students:data||[],count:Number(count||0)}}
export async function moveStudent(userId:string,institutionId:string,studentUserId:string,classId:string|null){await access(userId,institutionId,['owner','admin','coordinator']);if(classId){const{data}=await supabase.from('mindsteps_school_classes').select('id').eq('institution_id',institutionId).eq('id',classId).eq('status','active').maybeSingle();if(!data)throw new Error('Turma não encontrada nesta instituição')}const{data,error}=await supabase.from('mindsteps_student_links').update({class_id:classId}).eq('institution_id',institutionId).eq('user_id',studentUserId).select('*').single();if(error)throw new Error(error.message);await audit(institutionId,userId,'student.class.change',studentUserId);return data}
export async function setStudentEnrollment(userId:string,institutionId:string,studentUserId:string,status:'active'|'inactive'){await access(userId,institutionId,['owner','admin','coordinator']);const{data,error}=await supabase.from('mindsteps_student_links').update({status,left_at:status==='inactive'?new Date().toISOString():null}).eq('institution_id',institutionId).eq('user_id',studentUserId).select('*').single();if(error)throw new Error(error.message);await audit(institutionId,userId,status==='inactive'?'student.enrollment.end':'student.enrollment.restore',studentUserId);return data}
