import {Link} from 'react-router-dom'
import {BookOpen,Building2,GraduationCap,HeartHandshake,ShieldCheck,Target} from 'lucide-react'
const LEARN=[{label:'Tutor',route:'/chat'},{label:'Meu painel',route:'/dashboard'},{label:'Independência',route:'/independencia'},{label:'Learning Passport',route:'/passport'},{label:'Jornada',route:'/journey'},{label:'Missões',route:'/missoes'}]
const PEOPLE=[{label:'Aluno',route:'/auth?mode=register'},{label:'Professor',route:'/professor'},{label:'Família',route:'/familia'},{label:'MindSteps para Escolas',route:'/escola'}]
const TRUST=[{label:'Como aprendemos',route:'/como-aprendemos'},{label:'Aprendizagem responsável',route:'/aprendizagem-responsavel'},{label:'Transparência da IA',route:'/transparencia-ia'},{label:'Direitos & Dados',route:'/direitos-dados'},{label:'Acessibilidade',route:'/acessibilidade'},{label:'Segurança',route:'/seguranca'}]
export function Footer(){return <footer className="border-t border-slate-900 bg-slate-950 text-slate-300"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="grid gap-10 lg:grid-cols-[1.35fr_.7fr_.7fr_.85fr]"><div><Link to="/" className="inline-flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-primary-500 to-secondary-500"><BookOpen className="h-5 w-5 text-white"/></div><div><p className="text-xl font-black text-white">Mind<span className="text-primary-400">Steps</span></p><p className="text-xs font-bold text-slate-500">Meu espaço de aprendizagem</p></div></Link><h3 className="mt-6 max-w-md text-2xl font-black text-white">IA para aprender melhor — e depender menos dela.</h3><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">Aprendizagem personalizada para estudantes, com inteligência para professores, famílias e escolas acompanharem se a assistência está realmente se transformando em autonomia.</p><div className="mt-6 flex flex-wrap gap-2"><Badge icon={<Target/>} text="Autonomia"/><Badge icon={<ShieldCheck/>} text="IA responsável"/><Badge icon={<GraduationCap/>} text="Professor no centro"/></div></div><Column title="Aprender" links={LEARN}/><Column title="Para você" links={PEOPLE}/><Column title="Confiança" links={TRUST}/></div><div className="mt-10 grid gap-3 sm:grid-cols-3"><Signal icon={<GraduationCap/>} title="Professor" text="Evidências e intervenção pedagógica."/><Signal icon={<HeartHandshake/>} title="Família" text="Evolução explicada e autonomia como objetivo."/><Signal icon={<Building2/>} title="Escola" text="Learning OS, implantação e governança."/></div><div className="mt-9 flex flex-col gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 px-5 py-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-bold text-white">Desenvolvido por Alternative Ventures Ltda.</p><p className="mt-1 text-xs text-slate-500">CNPJ 61.920.356/0001-38</p></div><Link to="/empresa" className="text-sm font-bold text-primary-300 hover:text-white">Conhecer a empresa desenvolvedora</Link></div><div className="mt-7 flex flex-col gap-3 border-t border-slate-800 pt-7 text-xs text-slate-500 md:flex-row md:items-center md:justify-between"><p>© {new Date().getFullYear()} MindSteps. Aprenda com IA. Consiga sem ela.</p><div className="flex flex-wrap gap-4"><Link to="/empresa" className="hover:text-white">Alternative Ventures</Link><Link to="/seguranca" className="hover:text-white">Segurança</Link><Link to="/direitos-dados" className="hover:text-white">Direitos & Dados</Link><Link to="/acessibilidade" className="hover:text-white">Acessibilidade</Link></div></div></div></footer>}
function Column({title,links}:{title:string;links:Array<{label:string;route:string}>}){return <div><h4 className="mb-4 font-black text-white">{title}</h4><ul className="space-y-2.5 text-sm">{links.map(x=><li key={x.route+x.label}><Link to={x.route} className="text-slate-400 hover:text-white">{x.label}</Link></li>)}</ul></div>}
function Badge({icon,text}:{icon:React.ReactNode;text:string}){return <span className="inline-flex items-center gap-1.5 rounded-full border border-slate-800 bg-slate-900 px-3 py-1.5 text-xs">{<span className="[&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span>}{text}</span>}
function Signal({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-800 text-primary-300 [&>svg]:h-5 [&>svg]:w-5">{icon}</div><div><p className="text-sm font-black text-white">{title}</p><p className="mt-1 text-xs text-slate-500">{text}</p></div></div>}
